### ISSUE TITLE
Can't see peoples content and other people cant see page content I have added

### ISSUE THREAD

**Issue by ozdeadmeat** [docmost/docmost#104]
I am running through a reverse proxy (nginx), I have turned off caching etc, but we cant see any of each others content.

**Comment by Philipinho** [comment]
Do the pages appear on the sidebar ?

**Comment by ozdeadmeat** [comment]
The pages on the sidebar come up immediately. But the pages are blank.

**Comment by ozdeadmeat** [comment]
<img width="1914" alt="User1" src="https://github.com/user-attachments/assets/5bacfdeb-ab78-40c5-9858-ee1a419df359">
<img width="1898" alt="User2" src="https://github.com/user-attachments/assets/9b11385a-aee8-4ebe-881e-83a06dc0b6be">

**Comment by ozdeadmeat** [comment]
Site is being hosted from behind an nginX Proxy Manager Proxy and a cloudflare proxied domain name.

**Comment by Philipinho** [comment]
Check the websocket “WS” network tab on your browser. Please confirm if “collab” is connected and transmitting data when you type.

**Comment by ozdeadmeat** [comment]
do i need websockets? Is there a config guide for setting up this behind a proxy?

**Comment by ozdeadmeat** [comment]
Make sure to enable web sockets on your reverse proxy. Issue resolved, reverse proxy misconfiguration. Verified Config attached
<img width="612" alt="image" src="https://github.com/user-attachments/assets/04f4f522-ace7-411b-a0b1-151c9f8f7c97">

**Comment by Philipinho** [comment]
Glad you figured it out.

**Comment by Keric28** [comment]
Just dropping a comment that the above config is only half of the solution (at least it was for me) and figured I'd drop additional info in case anyone else needed it:
The below info is needed in the advanced tab under custom config
    location /ws {
        proxy_pass **http://IPaddress:PORT**;
        proxy_http_version  1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    
    
![image](https://github.com/user-attachments/assets/cb1b15d0-182c-4542-9a56-5c182781adbd)
