### ISSUE TITLE
What Mobile app can be used with Docmost ?

### ISSUE THREAD

**Issue by DarkXero-dev** [docmost/docmost#105]
Hello

I have just deployed Docmost but was wondering what mobile app can be used with it ? Would be great if we could sync across devices.

BTW I wrote an article about it on my site.
https://xerolinux.xyz/posts/docmost-notes/

Thanks and great job

**Comment by e-p-s** [comment]
Sadly noone :) thanks for your work.

**Comment by DarkXero-dev** [comment]
@e-p-s 

No problem a good tool deserves good coverage. Hoping to see support for multiple devices at some point. Great job...

**Comment by ados8** [comment]
Just install the web app

**Comment by Philipinho** [comment]
No plans for mobile app at this time. I will revisit the idea in the future.

Thank you for writing about Docmost.

**Comment by hillct** [comment]
The obvious solution is to offer a MediaWiki compatible API, then rebuild the Wikipedia apps for Android and iOS, adding a configurable endpoint. Admittedly, it's not trivial, but a reasonable strategy forward.
