### ISSUE TITLE
Members Permissions-Account Privacy-limit

### ISSUE THREAD

**Issue by staofr** [docmost/docmost#106]
Users can see each other's information, email and username.
Is it possible to see only his own information?
![221439mSun2020](https://github.com/user-attachments/assets/55a8740d-a2de-453c-ba19-020d5372eced)

**Comment by Philipinho** [comment]
This is by design. Docmost is designed to be used in a company-like setting where users are considered trusted.
There will only be a need to hide user information like email if we have support for  "Guest" accounts.

**Comment by SergkeiM** [comment]
Hi @Philipinho 

Docmost is exactly what I was looking for for our Internal Documentation,

But our use case requires to hide Groups and Members, becuase we are creating accounts for our Partners and we don't want them to see emails of other partners.

So they are Trusted users but we prefer to not show this info.

Maybe you need to consider such use case. thank you.

**Comment by Philipinho** [comment]
@SergkeiM, thank you for your input.
Would a restricted "Guest" account role (not yet implemented) not work for your use case?

**Comment by SergkeiM** [comment]
Hi @Philipinho 

I'm not sure i correctly understand the "Guest" users, They need account?

Also I was thinking maybe Multiple WorkSpaces can solve this, similar to what getoutline does: https://www.getoutline.com/changelog/multiple-workspaces
