### ISSUE TITLE
Content out of sync

### ISSUE THREAD

**Issue by simonzcx** [docmost/docmost#110]
I edited my deployed docmost in chrome, and when I finished editing, I switched to the edge browser, and the content I edited was not synced

**Comment by Philipinho** [comment]
Can you check the “WS” network tab if the `/collab` websocket path transmits data when you type on the editor?

**Comment by simonzcx** [comment]
sorry, I'm not a professional. Can you see the problem in my screenshot?
![Uploading Snipaste_2024-07-25_14-56-16.png…]()

**Comment by simonzcx** [comment]
<img width="1504" alt="Snipaste_2024-07-25_14-56-16" src="https://github.com/user-attachments/assets/dd6a8411-bb3c-47b9-86b1-cb4e9b77daa4">
sorry, I'm not a professional. Can you see the problem in my screenshot?

**Comment by mbreese** [comment]
How did you deploy it and how are you accessing the page? I deployed it behind an Nginx proxy and it didn't work at all until I added a few extra settings in my nginx.conf file.


       location / {
        proxy_pass http://localhost:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
   }

**Comment by ados8** [comment]
@simonzcx ensure your proxy has websockets turned on.

**Comment by simonzcx** [comment]
ok tks. I have found a problem with my synology agent not enabling websockets

**Comment by nuclearpolygon** [comment]
> @simonzcx ensure your proxy has websockets turned on.

Thanx a lot! you saved my day!

**Comment by BloodSugar327** [comment]
> @simonzcx ensure your proxy has websockets turned on.

THANK YOU! Set this up on NGINX and it works now 😁
