### ISSUE TITLE
having troubles installing in unraid docker 

### ISSUE THREAD

**Issue by darkwst** [docmost/docmost#112]
![Screenshot 2024-07-23 182926](https://github.com/user-attachments/assets/79bae3fe-7485-457d-b5d7-4136ee9e8f63)
![Screenshot 2024-07-23 182524](https://github.com/user-attachments/assets/4a43315a-14cb-4365-ae60-58c1bbdd789a)
![Screenshot 2024-07-23 141240](https://github.com/user-attachments/assets/676b269e-7583-4c41-9dfa-6aa7114ff750)

these are my settings 
postgresql://docmost:My_Password@db:5435/docmost?schema=public
my redis
redis://192.168.100.8:6379

my Postgres version 

PostgreSQL_Immich

Unraid version 
Unraid server Pro, version 6.12.6

i used ZappyZap repo 

does anyone have their settings working fine am i missing something, i would really appreciate the help tried everything I'm stuck <3

**Comment by devzwf** [comment]
Hello @darkwst 
i am the template author 
in : postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public
should be :
postgresql://docmost:STRONG_DB_PASSWORD@<DB_SERVER>:5432/docmost?schema=public
where 
- <DB_SERVER>  should be replace with the name of your postgres server (PostgreSQL_Immich in your case)
- STRONG_DB_PASSWORD should be replace with the password of the user docmost on your postgres server 

Also : 
you must create the user / Db in postgras prior
you can use either adminer / phpPgAdmin  to do so

I do not think the container is able to do so as it do not have the root password of the db

Let me know

**Comment by darkwst** [comment]
*thats my setup didnt work for some reason same issue 
* downloaded new database its Postgres alpine changed the name to alpine tried over nah same thing 
*downloaded adminer now next step searching how the hell are you supposed to use it to add user information lol 

*postgresql://docmost:59G@63dv!m8C6B@alpine:5433/docmost?schema=public 

********** thanks for taking the time to reply your a real one ***********

**Comment by devzwf** [comment]
please make sure no `@` sign in your password 
is your postgresql instance is "alpine"

can you please post the ouput of :
` docker ps |grep -i postgres`

**Comment by darkwst** [comment]
@devzwf

![Screenshot 2024-07-26 091533](https://github.com/user-attachments/assets/dc1ee280-7d99-4dfc-92ff-c825a982a94e)


postgresql://docmost:x5st7EVTym9q8@alpine:5433/docmost?schema=public

![Screenshot 2024-07-26 091426](https://github.com/user-attachments/assets/1f13b2e0-465e-476c-a068-2b7e0aad1404)


![image](https://github.com/user-attachments/assets/3318b491-c889-4fe5-ba68-c935f981f314)

**Comment by ados8** [comment]
@darkwst don't use alpine due to feature limitations.

- Run full Postgres (15 works)
- Ensure no special characters in password, increase length
- Ensure if using docker name they are within the same docker network
- Ensure docker permissions is set accordingly (1000 on Unraid appdata)

**Comment by darkwst** [comment]
You legends thanks so much.... its working fine now

both of you been kind and helpful ... 
@ados8
@devzwf

**Comment by devzwf** [comment]
Oh great
Thanks @ados8  for all the good point , i really assume  this was known.... my fault
@darkwst now you can enjoy an excellent app , dont forget to show your appreciation to the devs ;)

**Comment by darkwst** [comment]
@devzwf Will do. Thanks again. Yeah, that's the thing. It's always the stupid little things that mess everything up. Turned out PostgreSQL 15 was the answer!

**Comment by devzwf** [comment]
please mark this issue as closed :)
