### ISSUE TITLE
Why docker?

### ISSUE THREAD

**Issue by donnyv** [docmost/docmost#114]
Curious why use docker to install? It looks like its typescript running on nodejs. Should be pretty easy to setup.

**Comment by martinschilliger** [comment]
Why not? 😇

But its possible without, just build the environment on your machine by yourself if you want. Have a look at this ticket for some hints:

https://github.com/docmost/docmost/issues/67

**Comment by donnyv** [comment]
Why not....because not everyone uses docker. Its just another thing that needs to be setup. This is just a straight web app. Its not running multiple services.

**Comment by martinschilliger** [comment]
Yeah I understand, then you are free to run it without. Its not necessary, just easier for most people.

**Comment by nktrjsk** [comment]
Pls close, guy confused :heart:

**Comment by k8ieone** [comment]
@donnyv Because it's pretty much the simplest way to deploy *anything*. It's where everyone and everything is headed because it minimizes maintenance overhead.

Plus having a container image makes it possible to use with Kubernetes and create a highly-available instance.
