### ISSUE TITLE
Docker docmost container Failed to execute migration

### ISSUE THREAD

**Issue by flinthamm** [docmost/docmost#117]
I'm using the default docker-compose file and have setup the 4 key variables: APP_URL, APP_SECRET, DATABASE_URL,REDIS_URL. Very early on in the boot as the docmost container boots for the first time it completes the first 11 migration rows but then fails near the end with...
```
docmost-docmost-1  | [Nest] 41  - 07/24/2024, 1:10:29 PM   ERROR [DatabaseMigrationService] Failed to execute migration "20240324T086800-pages-tsvector-trigger"
docmost-docmost-1  | [Nest] 41  - 07/24/2024, 1:10:29 PM   ERROR [DatabaseMigrationService] Failed to run database migration. Exiting program.
docmost-docmost-1  | [Nest] 41  - 07/24/2024, 1:10:29 PM   ERROR [DatabaseMigrationService] error: syntax error at or near "TRIGGER"
docmost-docmost-1  | /app/apps/server:
docmost-docmost-1  |  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  server@0.2.8 start:prod: `cross-env NODE_ENV=production node dist/main`
docmost-docmost-1  | Exit status 1
docmost-docmost-1  |  ELIFECYCLE  Command failed with exit code 1.
docmost-docmost-1 exited with code 0
```
The main difference to the docker-compose script is I'm using an external PostgresSQL (v13.14) database but this runs fine for all other containers that use it.

Here is a screenshot of the errors.
![image](https://github.com/user-attachments/assets/8941ff91-b6f3-41b6-88e0-0620c32c8655)

I've tried deleting the database and running again. The user specified has full permissions. 

If anyone has any ideas, all gratefully received :)

**Comment by olivierIllogika** [comment]
The "CREATE OR REPLACE TRIGGER" syntax is only valid in [postgresql 14+](https://www.postgresql.org/docs/14/sql-createtrigger.html) ([vs. 13](https://www.postgresql.org/docs/13/sql-createtrigger.html))

Maybe the [documentation](https://docmost.com/docs/self-hosting/development) should indicate support for >=14, but if you tweak the migration to remove the "OR REPLACE" and it's the only issue, maybe the migration could be modified manually in the repo?

**Comment by flinthamm** [comment]
Hi @olivierIllogika and thank you for this detailed and prompt response. Potentially I'll look to upgrade my version or as you say, tweak the migration. 

Hopefully this might help someone else with a similar compatibility issue.
