### ISSUE TITLE
Is possible make a link public or a space public?? 

### ISSUE THREAD

**Issue by nikozrh** [docmost/docmost#125]
Thanks for share this amazing project, 

How can i make public some part of the documentation? and how can i customize a export in PDF? 

![Screenshot from 2024-07-25 16-57-49](https://github.com/user-attachments/assets/09b957d2-c142-43ab-905f-0a7ae561fbf1)

**Comment by Philipinho** [comment]
It’s not yet possible to make it public, but I have plans for it.

What do you wish to customize in the PDF export?

**Comment by nikoz84** [comment]
For example if you need to add a image in the header.

**Comment by Philipinho** [comment]
Hi @nikoz84, it is not yet possible to add header photos to pages.

**Comment by justurn** [comment]
a public space / guest account acccess would be an awesome feature

**Comment by Philipinho** [comment]
Closing in favor of #23.

**Comment by whizyrel** [comment]
Hello everyone,
I just wanted to ask if this made it as a feature yet.
If it has not, I will be willing to contribute. For the most part, I am from the Angular, Java part of this world.

**Comment by Sewdohe** [comment]
> Hello everyone, I just wanted to ask if this made it as a feature yet. If it has not, I will be willing to contribute. For the most part, I am from the Angular, Java part of this world.

I was coming to ask the same. I really like this software, but I need to use it as a publicly available wiki. I don't want everyone to have to make an account

**Comment by Philipinho** [comment]
@whizyrel, not yet implemented. You can follow #23.
