### ISSUE TITLE
in setting. Profile photo change is not working

### ISSUE THREAD

**Issue by jisik** [docmost/docmost#127]
in setting. Profile photo change is not working.
I want to use custom image file rather than Name label :)

**Comment by olivierIllogika** [comment]
Hey @jisik , it seems to be working for me. What's your storage config? Are you able to upload an image in a regular page?

Other details might be useful like your environment (docker, host OS), errors logs, what you see happening on screen: is the profile image changing, but not saving or is the file not changing after the file dialog box selection?

**Comment by ados8** [comment]
Also works for me, would say your docker permissions are incorrect and thus the image cannot be saved to data directory.

**Comment by jisik** [comment]
> Hey @jisik , it seems to be working for me. What's your storage config? Are you able to upload an image in a regular page?
> 
> Other details might be useful like your environment (docker, host OS), errors logs, what you see happening on screen: is the profile image changing, but not saving or is the file not changing after the file dialog box selection?

I solved.:) 
The problem is permission. 
I'm using synology container manager. (windows 11 + vmware workstation(xpenology 7.x version RDM).

I changed permission everyone (read -> read/write). 
https://kb.synology.com/ko-kr/DSM/tutorial/Docker_container_cant_access_the_folder_or_file
