### ISSUE TITLE
Bug: CSS legibility issues

### ISSUE THREAD

**Issue by ados8** [docmost/docmost#129]
Certain elements of the CSS style are very hard to see, further impacted to those with vision impairments.
I've noticed this the most with </> code function.
Here is an example of text in dark mode with normal formatting and with code formatting.
![image](https://github.com/user-attachments/assets/7d2bd148-b513-4547-9e7e-2e033ade80ef)
You can barely read the code formatting and this is only slightly better in normal mode.
Sadly you can't change the text color with this formatting on.
Thinking CSS dark mode text should remain white and normal mode black.

**Comment by Philipinho** [comment]
This has been fixed in v0.2.10.
