### ISSUE TITLE
Add Page References Easily

### ISSUE THREAD

**Issue by Spikeysanju** [docmost/docmost#132]
## Description:

It would be helpful to have a way to link to other pages within a document, like Notion.

## Expected Behavior:

When you press "/" and then click "Add page", you should be able to search for and add pages to the document.

**Comment by ados8** [comment]
I've already requested this one.
https://github.com/docmost/docmost/issues/100

**Comment by bolavefasfas** [comment]
> ## Description:
> It would be helpful to have a way to link to other pages within a document, like Notion.
> 
> ## Expected Behavior:
> When you press "/" and then click "Add page", you should be able to search for and add pages to the document.

+1 
This is must feature 

Though Now what I am doing to bypass this is very painful create apge manuaaly and paste it as a link.

**Comment by bolavefasfas** [comment]
> I've already requested this one. #100

Any eta ?

**Comment by Philipinho** [comment]
Closing in favor of https://github.com/docmost/docmost/issues/100.
