### ISSUE TITLE
Page content not saved

### ISSUE THREAD

**Issue by MadMax411** [docmost/docmost#133]
Hello there!

I'm creating / editing a page on one computer, open the page later an a second computer and only the title of the page is available. Sometimes it is possible to restore the content via page history. 

Has anyone an idea how to debug or where to search for the error? Is there a way to manually save a page while editing?

Thanks,
    Markus

Edit: Using version 0.2.8 (Docker:latest)

```
docmost-1  | > docmost@0.2.8 start /app
docmost-1  | > pnpm --filter ./apps/server run start:prod
docmost-1  | 
docmost-1  | 
docmost-1  | > server@0.2.8 start:prod /app/apps/server
docmost-1  | > cross-env NODE_ENV=production node dist/main

```

**Comment by ados8** [comment]
Definitely not experiencing that issue.
I've ported all my Bookstack data over and no issues.
I suspect you have a docker permissions issue and it can't save accordingly.

**Comment by Philipinho** [comment]
@MadMax411 can you confirm from your browser’s console “WS” network tab if the `/collab` websocket path is transmitting data when you type?

**Comment by MadMax411** [comment]
I have checked it on several computers and networks. It seems to be a problem in a company network. Sorry for opening the issue.
