### ISSUE TITLE
Inconsistent paragraph / element spacing

### ISSUE THREAD

**Issue by jasonvanhattum** [docmost/docmost#135]
The spacing between different elements and paragraphs on a page is inconsistent and unbalanced. 

I'm comfortable with the spacing between text paragraphs but there is extra whitespace between text paragraphs and tables and callouts.

The spacing between text elements and bulleted list elements is probably fine but the space between bulleted list items is too large.

I realise people have different preferences for line and paragraph spacing but I hope most people would generally agree with my screenshot below:

![CleanShot 2024-07-31 at 20 33 52](https://github.com/user-attachments/assets/38a23d66-3ed0-4f40-9c14-80474a3d6ce5)

**Comment by Philipinho** [comment]
Could you please try the latest version and give your feedback?
