### ISSUE TITLE
Disable spellcheck highlighting

### ISSUE THREAD

**Issue by andysmithfal** [docmost/docmost#136]
I am using Docmost for a lot of technical documentation. Spellcheck makes this type of note very difficult to read because of the spellcheck highlighting. 

This should be disabled at least for code blocks, but perhaps it should also be disabled for any block that is not currently being edited? 

![image](https://github.com/user-attachments/assets/9c12ed87-55e5-44a1-bf1c-45d8257b0c13)

**Comment by Philipinho** [comment]
I will consider adding a preference to disable spellcheck.

**Comment by Philipinho** [comment]
Spellcheck is now disabled in code blocks in v0.2.10.

**Comment by andysmithfal** [comment]
This is a huge improvement, thank you!
