### ISSUE TITLE
Bug: Pasting images from the clipboard does not work.

### ISSUE THREAD

**Issue by RKLBusinessDevelopment** [docmost/docmost#138]
When pasting an image from the clipboard, it is not added to the document. The screen flashes briefly and the image is not visible in the document.

**Comment by Philipinho** [comment]
Please check the browser console XHR requests tab if there are any errors while uploading.

**Comment by RKLBusinessDevelopment** [comment]
There is indeed an error:
{
    "message": "Request failed with status code 400",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 400\n    at $z (http://192.168.178.35:8094/assets/index-PRSZGbBN.js:69:1046)\n    at XMLHttpRequest.d (http://192.168.178.35:8094/assets/index-PRSZGbBN.js:69:5909)\n    at fw.request (http://192.168.178.35:8094/assets/index-PRSZGbBN.js:71:1963)\n    at async kV (http://192.168.178.35:8094/assets/index-PRSZGbBN.js:490:49721)\n    at async onUpload (http://192.168.178.35:8094/assets/index-PRSZGbBN.js:605:5630)\n    at async http://192.168.178.35:8094/assets/index-PRSZGbBN.js:601:26848",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http",
            "fetch"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "multipart/form-data",
            "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTkwOTM2ZS02MmVlLTcyMWQtYWI5YS0zYjRkMWM0ZWU4OGQiLCJlbWFpbCI6InN0aW5nQG5hcy5kZSIsIndvcmtzcGFjZUlkIjoiMDE5MDkzNmUtNjM1NS03NWY4LTg1ODctYTJiOTZmNjY3NGUyIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTcyMjE1MjE5MCwiZXhwIjoxNzI0NzQ0MTkwLCJpc3MiOiJEb2Ntb3N0In0.x7c48-27iZ1XrwPKZ6e4p2Sv8I3R_yLvhJjUcIfyTDo"
        },
        "baseURL": "/api",
        "withCredentials": true,
        "method": "post",
        "url": "/files/upload",
        "data": {}
    },
    "code": "ERR_BAD_REQUEST",
    "status": 400
}

**Comment by Philipinho** [comment]
I deleted your previous comment as it contains your JWT token which exposes your email.

Please paste the Docmost server logs.

**Comment by RKLBusinessDevelopment** [comment]
The used E-Mail is fake, as I'm running Docmost locally only. Thanks for taking care in any case, much appreciated! I have checked the server logs, it was a permission problem, I had to give root access to the "storage" directory and pasting images works now.

**Comment by Philipinho** [comment]
Glad to know you figured it out.
