### ISSUE TITLE
Feature Request: Add automatically generated "Table of Content" to the side bar

### ISSUE THREAD

**Issue by RKLBusinessDevelopment** [docmost/docmost#139]
One feature I would really love to see in Docmost is an automatically generated table of content. Trilium has such functionality and it is super useful for technical presentations for example, see attached screenshot that shows this feature in Trilium. 
![image](https://github.com/user-attachments/assets/60478918-e2fb-425e-b4d5-71284465935f)

**Comment by Philipinho** [comment]
Noted. Closing in favor of #95.
