### ISSUE TITLE
First item of the list doesn't continue after finishing nested list

### ISSUE THREAD

**Issue by sabirovrinat85** [docmost/docmost#141]
It seems that I can't do something like this:

1. First block level begins
    Here some text too, then nesting:

    - Nested block level begins
    - Nested block continues
    
    **Continue text of the first item of _first_ block level**
3. First block level list continues counting
4. And so on

Instead of continuing text it just stuck tied with last item of the nested block level list

ADDED: managed to do it somehow by dragging all block with last item of the nested block and tied text that supposed to be belonging to first block level, it got its number as second item of the first block level, then I made it again as nested block level and leftover text is finally untied to be under the first block level

**Comment by Amitrochates** [comment]
Hi, I wish to work on this, how do I replicate this?

**Comment by Amitrochates** [comment]
can this be assigned to me

**Comment by sabirovrinat85** [comment]
That's odd, but today tomorrow I started to edit again and everything seems to be fine now. Maybe some issues with a browser or application had rendering errors.

**Comment by Philipinho** [comment]
Feel free to reopen if you experience this again.
