### ISSUE TITLE
Flickering mouse and name tag

### ISSUE THREAD

**Issue by ddkooker2** [docmost/docmost#143]
While on a page edditing content with multiple users i can see the curser of the other person, while normally only the cursor would be blinking now the whole screen is blinking

![2024-08-05_16h18_04](https://github.com/user-attachments/assets/19c0cb6b-2acb-43d0-bf10-4544ced62835)

**Comment by ddkooker2** [comment]
Both me and my colleague are working on laptops not on tablet, didn't check nor do I have the opportunity to test it on a tablet sorry.

It's in a closed network where we cannot access it without using a jump host

**Comment by Philipinho** [comment]
Feel free to reopen if this issue persists in the latest version.
