### ISSUE TITLE
Images not working? (in firefox - chrome-based okay)

### ISSUE THREAD

**Issue by spinningD20** [docmost/docmost#15]
Howdy!  Saw you on hacker news and am in the market for a self-hosted collab documentation system.

I loaded things up and everything I've tried seems to be working, with the exception of images.  No S3 config or anything here, all local.  

https://github.com/docmost/docmost/assets/3946418/258e55e1-295c-4c10-9c31-2a4cee9268c4

I recorded a quick video.

As I was about to submit this, my QA/troubleshooting background reminded me that I am using firefox and should try a different browser.  

**It all works just fine in chromium**, so this is likely just browser compatibility.  Either way, submitting the issue, in case you wanted to know!

Best of luck!

**Comment by Philipinho** [comment]
Thanks for reporting. I will do some investigating.

**Comment by osresearch** [comment]
I see the same behaviour in Firefox on Linux both with uploading images via `/` as well as pasting an image with Control-V.

**Comment by denysvitali** [comment]
It looks like the upload itself is fine - it's the image rendering that seems to be broken on Firefox.
If you upload an image in Firefox, like in the video, and then open the page in Chrom{ium,e}, you'll see the result.

**Comment by Philipinho** [comment]
Please upgrade to v0.2.2 to get the fix.

Upgrade guide: https://docmost.com/docs/installation#upgrade

**Comment by ados8** [comment]
Having the same problem on Chromium and version 0.2.7
