### ISSUE TITLE
Home button missing on mobile layout 

### ISSUE THREAD

**Issue by pxlnic** [docmost/docmost#151]
I've been starting to use Docmost on my phone and I noticed the "Home" button disappears in the mobile layout. As far as I've seen, there is no other option to get back to the main page to change to a different space. 

I have been able to work around it by rotating my phone to get it into a wider view which brings back the home button.

**Comment by Amitrochates** [comment]
I'd like to work on this

**Comment by Philipinho** [comment]
The "Home" button is not visible on mobile due to responsiveness concerns.

@Amitrochates, feel free to create a PR to add the home link to the "Docmost" logo. This should make it a little better.

**Comment by Philipinho** [comment]
Fixed in v0.3.0.
