### ISSUE TITLE
Content of pages missing on other browsers/devices - docker 

### ISSUE THREAD

**Issue by tinkermesomething** [docmost/docmost#156]
My Docmost instance is running dockerized and is accessed via a reverse proxy. 
I have populated my first space with some pages and corresponding content. 
When I use another browser or an incognito session to access my space, the pages are there by there is no content.
I can log out and login within the same browser session and will still find the content, however.

**Comment by Philipinho** [comment]
Is websocket enabled on your reverse proxy?

**Comment by tinkermesomething** [comment]
ah so that's what it was! 
I've enabled it and the content started showing as expected!
Thank you!!

**Comment by Zev-se** [comment]
For anyone finding this wondering how to set this up with own-certs and an nginx-reverse proxy here you go:
```
events {}
http {
	server {
    listen 80 default_server;
    server_name <SITE_URL>;
    return 301 https://<SITE_URL>$request_uri;
	}
	server {
    listen 443 ssl http2;
    server_name <SITE_URL>;

    ssl_certificate     /PATH/TO/certs/CERT.crt;
    ssl_certificate_key /PATH/TO/certs/KEY.key;

    location / {
        proxy_pass http://<CONTAINER_NAME>:<CONTAINER_PORT>; #Normally docmost:3000
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
	}
}
```

**Comment by tanjilbhuiyan** [comment]
I guess, it works for the new content. Not for the old content. so i have made the changes. logged out and logged in. The old content does not show. Now made a post,added some link. and in separate browser, we tried to browse the post and getting content.

**Comment by Philipinho** [comment]
@tanjilbhuiyan, could you please confirm if websockets work?

**Comment by tanjilbhuiyan** [comment]
I am assuming its working . As new posts seem to be working. Made changes to a different browser and got the change. Will again check.

**Comment by MortemThy** [comment]
> @tanjilbhuiyan, could you please confirm if websockets work?

I can confidently confirm, that **enabling websockets fixed the issue**.

It seems as if docmost stores dynamic content changes in cache (different for folder structure, as it was preserved) and writes to DB on connection stop.
And everything else is accessed by other users via Websockets.

I'm basing this off my expirement, in which page contents were empty before I enabled websockets, then, upon reloading the page on the machine I made those very pages on - the contents were avaliable _and_ there was the indication that other user is using the document. (In the form of caret with a name)

I hope this helps.

**Comment by tanjilbhuiyan** [comment]
@Philipinho 
Yes , Enabling Web Socket Fixed the issue. 

I have tested again. For by disabling and enabling web socket support. This time i did not face any issue like before like old pages not syncing. I guess that was error from my side. 

That for explanation. @MortemThy
