### ISSUE TITLE
[Feature Request] Folder/Hierarchy system

### ISSUE THREAD

**Issue by Gandalf-Le-Dev** [docmost/docmost#160]
How can i nest pages to have a folder/hierarchy system ?

**Comment by Philipinho** [comment]
Does the nested notes system not work for your use-case ?

**Comment by Gandalf-Le-Dev** [comment]
What do you mean ? Where can I see this feature I can't find it

**Comment by Philipinho** [comment]
Move your cursor to a page on the sidebar and the plus icon to create a child page will appear.

**Comment by Gandalf-Le-Dev** [comment]
I apologize deeply, I just saw the + sign on the right side ..... very sorry I feel dumb

**Comment by Gandalf-Le-Dev** [comment]
I'll change the feature request to be only the create space button as I was thinking of also having the possibility to link a page from another page but I think someone else suggested it

**Comment by bolavefasfas** [comment]
> Does the nested pages system not work for your use-case ?

We need to see the  neseted page in previous document. similar to notion.
![image](https://github.com/user-attachments/assets/93ec20a3-02cc-4fdb-ad0b-f13965d903a5)
we should be able to link the subpages to the current page to lcik and open it from the main page it seld and create subpages by /page

**Comment by JtMotoX** [comment]
I would really prefer to have folders. I am coming from Obsidian, and directory structures are very intuitive. Any way to do that?
