### ISSUE TITLE
Support s3ForcePathStyle for S3 storage

### ISSUE THREAD

**Issue by vosiander** [docmost/docmost#166]
Hi!

I'm using a selfhosted minio instance which does not support subdomain bucket urls: https://<bucket>.minio.example.com

Please add the s3ForcePathStyle configuration to the node aws s3 client configuration, so that I can enable it via env variables.

**Comment by dimitarnikolovv** [comment]
+ 1

**Comment by Philipinho** [comment]
Closed by https://github.com/docmost/docmost/pull/181.

**Comment by bolavefasfas** [comment]
> Hi!
> 
> I'm using a selfhosted minio instance which does not support subdomain bucket urls: https://.minio.example.com
> 
> Please add the s3ForcePathStyle configuration to the node aws s3 client configuration, so that I can enable it via env variables.

can you tell how did you use the subdomain minio I am trying to set up the same

**Comment by vosiander** [comment]
> > Hi!
> > I'm using a selfhosted minio instance which does not support subdomain bucket urls: https://.minio.example.com
> > Please add the s3ForcePathStyle configuration to the node aws s3 client configuration, so that I can enable it via env variables.
> 
> can you tell how did you use the subdomain minio I am trying to set up the same

`AWS_S3_ACCESS_KEY_ID=xxx
AWS_S3_SECRET_ACCESS_KEY=xxx
AWS_S3_BUCKET=docmost
AWS_S3_REGION=default
AWS_S3_URL=https://s3.example.com
AWS_S3_ENDPOINT=https://s3.example.com
AWS_S3_FORCE_PATH_STYLE=true`

Make sure to use the latest release of docmost or else it won't work
