### ISSUE TITLE
Workspace name input does not trim leading/trailing whitespace

### ISSUE THREAD

**Issue by r3Fuze** [docmost/docmost#17]
In the initial workspace setup and in the workspace settings, when setting/changing the name of the workspace, you're allowed to have leading/trailing white space.

In my case I tried using a 2 character long workspace name (example: `ab`), but got stopped by the 4 character minimum. For fun I tried adding two spaces after the name to reach the 4 character minimum (eg. `ab  `) and was surprised that it worked. It works exactly the same when changing the name in the workspace settings.

Having invisible characters in the name (the spaces are removed in for example the user dropdown in the navbar) can be confusing, and is probably not intended.

**Comment by Philipinho** [comment]
Thank you for catching this. I will fix it.

**Comment by ellieschieder** [comment]
I currently look into this (e.g. where this is the case.)

Using string transforms:
```typescript
const formSchema = z.object({
  name: z.string().trim().min(2),
  password: z.string().trim().min(8),
});
```

Instead of using them just as ```z.string().min(2)``` https://zod.dev/?id=strings 


Also -> Names (first names) with just 1 char are relatively common. So if I'm allowed to trim every field and set names to min 1, I would be happy to send a PR.

**Comment by Philipinho** [comment]
@ellieschieder, I am happy to review your PR.

You can set the minimum user name value to 1. It seems reasonable.

These two backend validations will need to be updated too.
https://github.com/docmost/docmost/blob/a0b31804d987547783435205e54f679af9e3fa4e/apps/server/src/core/auth/dto/create-user.dto.ts#L12

(Your changes will also help to fix the length discrepancy here. I just noticed.)
https://github.com/docmost/docmost/blob/a0b31804d987547783435205e54f679af9e3fa4e/apps/server/src/core/auth/dto/create-admin-user.dto.ts#L6

Just a heads-up, CLA is required when you send a PR, if that is okay with you.
Thank you.

**Comment by ellieschieder** [comment]
Thanks, the server side validation is what I in fact did not find so easy.

I also did set (extra commit) theme per default to auto. I hope that is okay.

**Comment by ellieschieder** [comment]
Ohhh also, I never worked with nextjs, where do I find the logic, that would allow me to also trim server side?

**Comment by ellieschieder** [comment]
Nest/Fastify, sorry.

**Comment by Philipinho** [comment]
I would prefer the default theme to be light since there is a theme preference in settings. I like the bright colors first 😃 

You can find both DTO files in `/apps/server/src/core/auth/dto`.
```
create-admin-user.dto.ts
create-user.dto.ts
```

Feel free to ask me any questions.

**Comment by ellieschieder** [comment]
I mean technically that’s why there is ```prefers-color-schema```:D

Thanks! Im on it :D

**Comment by olivierIllogika** [comment]
> @ellieschieder, I am happy to review your PR.
> 
> You can set the minimum user name value to 1. It seems reasonable.
> 
> These two backend validations will need to be updated too.
> 
> https://github.com/docmost/docmost/blob/a0b31804d987547783435205e54f679af9e3fa4e/apps/server/src/core/auth/dto/create-user.dto.ts#L12
> 
> (Your changes will also help to fix the length discrepancy here. I just noticed.)
> 
> https://github.com/docmost/docmost/blob/a0b31804d987547783435205e54f679af9e3fa4e/apps/server/src/core/auth/dto/create-admin-user.dto.ts#L6
> 
> Just a heads-up, CLA is required when you send a PR, if that is okay with you. Thank you.

Would creating a local file system package imported by both client and server, maybe called shared-constants, be a reasonable long term solution to this (and future possible) discrepancy?

**Comment by Philipinho** [comment]
Should be fixed here https://github.com/docmost/docmost/pull/397.
