### ISSUE TITLE
Cannot Upload Images in Safari

### ISSUE THREAD

**Issue by OldManUmby** [docmost/docmost#174]
When I try to upload an image with Safari (Version 18.0 (20619.1.24.11.2)), nothing happens. But I was allowed to upload a new avatar. Odd. When I switched to the ARC browser for testing, the images uploaded fine. I don't see any errors.

FYI: I know Safari is a beta version, but I just updated it. It wasn't working in the previous version either.

Suggestions/questions?

**Comment by Philipinho** [comment]
Closing in favor of https://github.com/docmost/docmost/issues/172.
