### ISSUE TITLE
Error with user account creation

### ISSUE THREAD

**Issue by Ultragian** [docmost/docmost#176]
When I send an email for a user to create an account and they input their data in, it tells them this:
**token must be a string**

So I can't create any new user.

![image](https://github.com/user-attachments/assets/286da1c6-a680-46fe-8977-c447c2a30e7b)

**Comment by Philipinho** [comment]
Can you confirm if the invite token is present or not in the url?

**Comment by Ultragian** [comment]
Checked it again. I think the security I have in front removed it after the first login. After I repasted the link when authorized by my system it worked.
Just have another issue now, I cannot delete the user that was accepted.

**Comment by Ultragian** [comment]
Is there no way to delete users?

**Comment by Philipinho** [comment]
Hi @Ultragian, there is no way to deactivate user accounts at this time. However, you can delete accounts directly from the database.
