### ISSUE TITLE
Be able to reset user password

### ISSUE THREAD

**Issue by sibelius** [docmost/docmost#182]
can you point it out how to implement this ?

**Comment by Morthor** [comment]
There's also no way for a user to recover their own password

**Comment by aldy505** [comment]
> There's also no way for a user to recover their own password

There is actually, by changing the Postgres row directly. It's just a regular password hash (I forgot whether it's bcrypt or argon2). 

I might implement a "change password" API endpoint later.

**Comment by Morthor** [comment]
> > There's also no way for a user to recover their own password
> 
> There is actually, by changing the Postgres row directly. It's just a regular password hash (I forgot whether it's bcrypt or argon2).
> 
> I might implement a "change password" API endpoint later.

I'm sorry, but that does not answer my comment. A user themselves cannot access the Postgres DB themselves to recover their password.
Does this mean that right now the only way would be for the admin to change the Postgres row to a new hashed password, tell that password to the user, and have them change after?

**Comment by aldy505** [comment]
> > > There's also no way for a user to recover their own password
> 
> > 
> 
> > There is actually, by changing the Postgres row directly. It's just a regular password hash (I forgot whether it's bcrypt or argon2).
> 
> > 
> 
> > I might implement a "change password" API endpoint later.
> 
> 
> 
> I'm sorry, but that does not answer my comment. A user themselves cannot access the Postgres DB to recover their password.
> 
> Does this mean that right now the only way would be for the admin to change the Postgres row to a new hashed password, tell that password to the user, and have them change after?

Sadly yes.

**Comment by Morthor** [comment]
That d

> > > > There's also no way for a user to recover their own password
> > 
> > 
> > > 
> > 
> > 
> > > There is actually, by changing the Postgres row directly. It's just a regular password hash (I forgot whether it's bcrypt or argon2).
> > 
> > 
> > > 
> > 
> > 
> > > I might implement a "change password" API endpoint later.
> > 
> > 
> > I'm sorry, but that does not answer my comment. A user themselves cannot access the Postgres DB to recover their password.
> > Does this mean that right now the only way would be for the admin to change the Postgres row to a new hashed password, tell that password to the user, and have them change after?
> 
> Sadly yes.

That does leave me very sad. I was about to expand the usage of DocMost from a small group to a few dozen users, but I can't be available to go into the docker instance running docmost, into postgres, to make this change every time someone forgets their password.
I really enjoy the simplicity of DocMost, it's a tool with great potencial, but without the basic authentication functionality and user management, it becomes unusable for most use cases.

**Comment by aldy505** [comment]
> > > > > There's also no way for a user to recover their own password
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > There is actually, by changing the Postgres row directly. It's just a regular password hash (I forgot whether it's bcrypt or argon2).
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I might implement a "change password" API endpoint later.
> 
> > > 
> 
> > > 
> 
> > > I'm sorry, but that does not answer my comment. A user themselves cannot access the Postgres DB to recover their password.
> 
> > > Does this mean that right now the only way would be for the admin to change the Postgres row to a new hashed password, tell that password to the user, and have them change after?
> 
> > 
> 
> > Sadly yes.
> 
> 
> 
> That does leave me very sad. I was about to expand the usage of DocMost from a small group to a few dozen users, but I can't be available to go into the docker instance running docmost, into postgres, to make this change every time someone forgets their password.
> 
> I really enjoy the simplicity of DocMost, it's a tool with great potencial, but without the basic authentication functionality and user management, it becomes unusable for most use cases.

It's a bummer for me, too. Our story seems similar 😆. But hey, it's still early, there are lots of room for improvement.

**Comment by Philipinho** [comment]
Password reset will be available in the next release.

**Comment by aldy505** [comment]
> Password reset will be available in the next release.

@Philipinho are you working on it yet? If you're not. I can implement that.

Basically the flow is:
1. Pass in the `email` of the user
2. User will receive an email with a certain code, only if their account exists on docmost.
3. User validate that code, put in a new password (with confirmation).

2 new API endpoints

**Comment by sahariardev** [comment]
@Philipinho and @aldy505 I want to develop the frontend

**Comment by sahariardev** [comment]
> There you go: #250
> 
> Does anyone want to implement the frontend side? I'm not really good with React, so.. yeah. I probably can't do that.

Here is the frontend side https://github.com/docmost/docmost/pull/273

**Comment by ddkooker2** [comment]
In the mean time, does anyone have the commands/procedure to manually reset the password?

**Comment by aldy505** [comment]
> In the mean time, does anyone have the commands/procedure to manually reset the password?

@ddkooker2 this one https://github.com/docmost/docmost/issues/182#issuecomment-2326401720

**Comment by quaintdev** [comment]
I am locked out of my account! Any other way we can reset the password?

**Comment by Philipinho** [comment]
@quaintdev If you can run a small node script, see https://github.com/docmost/docmost/issues/182#issuecomment-2326401720.

Otherwise, you could generate a 12-round password hash of your desired password from https://bcrypt-generator.com/. Then update the password manually in the Postgres db.

```bash
docker exec DB_CONTAINER_ID psql -U docmost -d docmost -c "UPDATE users SET password = 'PASSWORD_HASH' WHERE email = 'YOUR-EMAIL';"
```

**Comment by quaintdev** [comment]
> @quaintdev If you can run a small node script, see [#182 (comment)](https://github.com/docmost/docmost/issues/182#issuecomment-2326401720).
> 
> Otherwise, you could generate a 12-round password hash of your desired password from https://bcrypt-generator.com/. Then update the password manually in the Postgres db.
> 
> ```shell
> docker exec DB_CONTAINER_ID psql -U docmost -d docmost -c "UPDATE users SET password = 'PASSWORD_HASH' WHERE email = 'YOUR-EMAIL';"
> ```

This worked. Thanks!

**Comment by Philipinho** [comment]
Password reset UI.
Thanks to contributions from @aldy505 and @sahariardev.

**Ps:** It will be available in the next release.

<img width="993" alt="Screenshot 2024-09-19 at 15 52 54" src="https://github.com/user-attachments/assets/a989bd82-f5b1-49bc-87da-8cdd0d76df2d">

<img width="993" alt="Screenshot 2024-09-19 at 16 00 56" src="https://github.com/user-attachments/assets/6928598e-92dc-4e93-9a48-dbcd31a6d974">

**Comment by heinrihs-s** [comment]
When updating password hashes in PostgreSQL through a container's console in Portainer, you need to handle dollar signs (`$`) carefully as psql may interpret them as variable substitution markers.

```sql
psql -U docmost -d docmost -c "UPDATE users SET password = $pass$$2a$12$ZTMgX4lFWSSqKDeij4Q/W.Qb/fmzD3fAophfD8jpeWIqKlLhan02$pass$ WHERE email = 'user@example.com';"
```

**Comment by pomfei** [comment]
@Philipinho `docker exec DB_CONTAINER_ID psql -U docmost -d docmost -c "UPDATE users SET password = 'PASSWORD_HASH' WHERE email = 'YOUR-EMAIL';"`   
it doesn‘t work now，maybe the website hash is not right?

**Comment by southalan** [comment]
@pomfei 

> [@Philipinho](https://github.com/Philipinho) `docker exec DB_CONTAINER_ID psql -U docmost -d docmost -c "UPDATE users SET password = 'PASSWORD_HASH' WHERE email = 'YOUR-EMAIL';"` it doesn‘t work now，maybe the website hash is not right?

I might be a few months late, but I had a similar issue, let me give you an example:

```
Password: 123456
Hashed: $2a$12$yENzrI3ZewBAf8edKpsED.lXw3GXaC2HZL1zIJfzbizaLvV0M.O7e

docker exec DB_CONTAINER_ID psql -U docmost -d docmost -c "UPDATE users SET password = '\$2a\$12\$yENzrI3ZewBAf8edKpsED.lXw3GXaC2HZL1zIJfzbizaLvV0M.O7e' WHERE email = 'youruser@something.com';"
```
 
As heinrihs-s previously mentioned, you should escape the "$" dollar sign to avoid issues. 

If done correctly, you will get a "UPDATE 1" as a result, and the "$" will not be cut/replaced within the hashed password string. 

Cheers!
