### ISSUE TITLE
Feature request: Static links

### ISSUE THREAD

**Issue by Zev-se** [docmost/docmost#189]
As of now the link is https://mydomain.topdomain/s/title-of-page, this create a problem where links break as soon as someone updates the title. It would be nice with the option to switch this to some index-number or alike instead so that the title and the URL are independent of each other.

**Comment by Philipinho** [comment]
The links do not break because a static ID is added to each slug. e.g `title-of-page-sTBBbFQHh`.

**Comment by Zev-se** [comment]
Ohh! Must have missed this. Epic! Thanks!
