### ISSUE TITLE
GH Sponsor / Donation page

### ISSUE THREAD

**Issue by denysvitali** [docmost/docmost#19]
Hello there!

Your project looks amazing - and I think it would be nice if you continued to develop it while maintaining it AGPL.

Do you mind setting up a GH Sponsors page / Patreon / Donation link so that we can sponsor the development of this project?

Thanks!

**Comment by Philipinho** [comment]
Thank you for your suggestion.
At this time, I am not really open to accepting donations.

I have been working full-time on Docmost for the past year and plan to continue to do so (I fund it myself). 
I plan to offer a cloud version in the future. It's a long road from here though.
