### ISSUE TITLE
[Feature Request]: Implement TipTap Collaboration Cursor Extension 

### ISSUE THREAD

**Issue by Shadowfita** [docmost/docmost#209]
I think there could be value for teams in a large collaborative environment to have the option to enable or disable the collaboration cursor extension available for TipTap.

https://tiptap.dev/docs/editor/extensions/functionality/collaboration-cursor

**Comment by Philipinho** [comment]
The extension is already integrated.

**Comment by Shadowfita** [comment]
> The extension is already integrated.

My mistake! Thank you so much for this great project.
