### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by rsandrade** [docmost/docmost#21]
Hi,

May we have sqlite support? :)

**Comment by Philipinho** [comment]
Postgres is the only supported database.  
I believe it is good to focus on one DB and do it better. Adding support for other databases will lead to maintenance issues down the road, which I would like to avoid.

**Comment by xthz** [comment]
> Postgres is the only supported database. I believe it is good to focus on one DB and do it better. Adding support for other databases will lead to maintenance issues down the road, which I would like to avoid.

Thank you for your development work. I hope you can consider SQLite, which is very important for our users with limited hardware resources. And I think SQLite is enough for the data storage of note-taking software.
