### ISSUE TITLE
Unexpected page content saving behavior

### ISSUE THREAD

**Issue by thrvoic** [docmost/docmost#220]
I noticed confusing page content saving behavior.
When docmost is accessed via APP_URL and local_ip:port, using the same user account and workspace, the page content is saved independently. Page title and icon on the other hand are carried across.

Steps to reproduce:
1) Open https://mydocmost.example.com (session 1) and create "Page 1" with content "Text 1".
2) Open http://192.168.1.100:3000 (session 2). "Page 1" exists but it is empty.
3) In session 2, add "Text 2" as content.
4) Refresh session 1, "Text 1" is loaded.
5) Refresh session 2, "Text 2" is loaded.
6) In session 2, change the page name to "Page 2".
7) Refresh session 1, the page name is correctly loaded as "Page 2".

The expected behavior is that the URL does not affect page edits.

**Comment by Dunkon** [comment]
@thrvoic can you heck your browser console, do you have some errors there?

**Comment by thrvoic** [comment]
@Dunkon there was an issue with my reverse proxy configuration, WebSocket was not working properly. I didn't expect this as page creation, titles, and icons all looked correctly persisted. Now page content seems to sync properly.

I do however still see two errors in the console (for both URLs):
1) _TextSelection endpoint not pointing into a node with inline content (doc): LR @ index-DJdCLBd7.js:494_
2) _[HocuspocusProvider] An authentication token is required, but you didn’t send one. Try adding a `token` to your HocuspocusProvider configuration. Won’t try again. @ index-DJdCLBd7.js:596_

Is it that page content was saved in the browser local state, while page titles were correctly persisted in the database? I'm unfamiliar with `Y.js` and how it is used here.

Can I suggest you expose such errors in the UI? For example, the top banner message: "Internal connection error, page content won't be saved. Please check console log for details". It would be much less confusing.

**Comment by Dunkon** [comment]
@thrvoic yes, I expected the problem with WS and nginx reverse proxy because I had the same.
Probably the good idea is to add some nginx.sample.conf to prevent this in the future and add some lines to readme.

I have first error in console from you list as well but I don't see any impact in the app functionality for now.

Good error reporting is always the perfect idea, agreed.

**Comment by Philipinho** [comment]
@thrvoic disregard the console warnings. They cause no issues.

Y.js powers the editor’s real-time collaboration.
The page title works differently. It does not go through Y.js.

If the websocket fails to connect, the page’s Y.js state is stored in the browser’s indexeddb. It will be synced when connection is established.

Your suggestion is taken. 

Thank you.
