### ISSUE TITLE
Can not export page

### ISSUE THREAD

**Issue by betheboy** [docmost/docmost#231]
some pages can not export !
there comes a error report like "Export failed:undefined"

**Comment by Philipinho** [comment]
Can you please paste your server logs?

**Comment by betheboy** [comment]
> Can you please paste your server logs?

I couldn't find these logs.
![export](https://github.com/user-attachments/assets/7355b8b6-8072-4727-bc15-2c00489e4492)

**Comment by betheboy** [comment]
> Can you please paste your server logs?

I couldn't find these logs.
please tell me where to get it,thanks!
![export](https://github.com/user-attachments/assets/cf883240-3bd0-49aa-a785-0ec9b7dc46c4)

**Comment by Philipinho** [comment]
Use `docker logs CONTAINER_ID`.

**Comment by betheboy** [comment]
No logs came while i was exporting pages!!!






rabbit
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "docmost/docmost"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月5日(星期四) 上午6:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [docmost/docmost] Can not export page (Issue #231)





 
Use docker logs CONTAINER_ID.

**Comment by agiletuan** [comment]
> Can you please paste your server logs?

docmost "Invalid character in header content [\"content-disposition\"]"

**Comment by betheboy** [comment]
Could you please just tell me which log do you need?
Systemlog or container log?
Container logs shown nothing, like i told you befor.
Thanks!

**Comment by betheboy** [comment]
> Same with any cyrilic, non latinic language and emoji in page title. **workaround** just rename page to fully english name, and export will work.

Yeah,that's right. 
I tested that!
I think it will be solve in the futrue release.

**Comment by gadgetb0y** [comment]
I'm having this issue with exporting a specific space or subpages within the space. There are only english characters in the titles but most of them have emojis set in the UI - could emojis also be a problem? Again, they're not in the page title.
