### ISSUE TITLE
[Feature Request] Remove embeds

### ISSUE THREAD

**Issue by symphonyalpha** [docmost/docmost#233]
I'm currently trying to add some Youtube links to my pages but each link keeps showing up as an embed with no option to simply leave it as a URL/text like so: 

![image](https://github.com/user-attachments/assets/e38921ad-0da1-4357-be06-809a5385d886)

So far, this only applies with Youtube links. It would be nice to have the ability to choose whether to display something as an embed or not.

**Comment by kelke** [comment]
Not even inline code disables the youtube preview..
When pasting a youtube link in the middle of a line of inline code, the youtube preview is simply forced in place breaking the line.
The only way to get Docmost to not display a preview is inserting into a code-block or by typing by hand.

I believe this is not even a feature request anymore, just a bug.

**inline code without link**
<img width="459" alt="image" src="https://github.com/user-attachments/assets/1b7f7047-0c06-49d6-91c3-d2f40ee1d999">

**inserting the link breaks inline code**
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/a5bcdbab-8a97-4ef5-bfbe-7dd07006c271">

**Comment by Philipinho** [comment]
Automatic embed is now disabled for YouTube. A slash command has been added. 
Will be available in the next release.
