### ISSUE TITLE
Can't upload images into Docmost

### ISSUE THREAD

**Issue by bdorr1105** [docmost/docmost#234]
I am unable to load pictures into any of my spaces. When I select a picture, it uploads and shows for about a second and then disappears like I never uploaded it. I am using a docker compose installation.

**Comment by Philipinho** [comment]
Please check the server logs for any errors.

**Comment by moafrancky** [comment]
Hi,

I had the same problem. It was a permission issue on the docmost volume /app/data/storage. Set ownership to 1000:1000 to fix it.

**Comment by bdorr1105** [comment]
@moafrancky, am I adding that to the docker-compose.yml in the environment section?

**Comment by fengwang** [comment]
> Please check the server logs for any errors.

I had this problem with `image: docmost/docmost:0.3.1`
It appears the owner of `/app/data/storage` is user root instead of user node.
A quick fix might be executing `docker exec -it --user root docmost bash` and `chown -R node /app/data/storage`.

But is is better to have this problem fixed upstream.

**Comment by R-Nabil** [comment]
Hey.

I have the same problem. I'm running in docker rootless. THis solved it for me as well.

**Comment by AhmedBHameed** [comment]
Solved for me as well. Thank you @fengwang !

I wonder if there is a direct way in docker compose where I can set permission in advance.

I tried adding

```yml
environment:
  - PUID=1000
  - PGID=1000
```

But that did not work :(

**Comment by joezhouchenye** [comment]
Add `user: 0:0` works for me.

```
services:
  docmost:
    image: docmost/docmost:latest
    user: 0:0
    Other Contents...
```
