### ISSUE TITLE
[Feature Request] Shell Selection when Adding Code Blocks

### ISSUE THREAD

**Issue by bdorr1105** [docmost/docmost#238]
There is a pretty cool feature in notion which allows you to choose the kind of shell something is, so I can choose powershell, bash or whatever it is and I think it color codes the text based off that which would be super awesome.

![Screenshot 2024-09-02 130747](https://github.com/user-attachments/assets/e45b4ae2-fbdd-4f49-80cb-94f84927a71c)
![Screenshot 2024-09-02 130755](https://github.com/user-attachments/assets/67379f6d-7746-4820-b82e-ee180f207a76)

**Comment by Philipinho** [comment]
Already introduced in the just released [v0.3.0](https://github.com/docmost/docmost/releases/tag/v0.3.0).
