### ISSUE TITLE
Service is not listening on all interfaces

### ISSUE THREAD

**Issue by 56k-modem** [docmost/docmost#24]
I can access some other services on other ports via Tailscale, tried to access Docmost but it looks like it is configured not to accept connections on all interfaces:
```
http://hostname.lan:3000 - works
http://[tailscale IP]:3000 - doesn't work
```
Would it be possible to let us configure the listen address as 0.0.0.0 please?

**Comment by ellieschieder** [comment]
--host does that.

```bash
pnpm nx run client:dev --host
```

**Comment by 56k-modem** [comment]
Sorry if this should be obvious but how can I apply this in my docker-compose.yml? Tried `network_mode: host` but the service won't start that way.

**Comment by Philipinho** [comment]
The server already listens on 0.0.0.0.
https://github.com/docmost/docmost/blob/a0b31804d987547783435205e54f679af9e3fa4e/apps/server/src/main.ts#L64

I have not used Tailscape before, but I will research the issue more.

**Comment by 56k-modem** [comment]
This is now working after upgrading to v0.2.1, thank you.
