### ISSUE TITLE
[Feature Request] Add Custom Icons

### ISSUE THREAD

**Issue by bdorr1105** [docmost/docmost#240]
When creating pages, I like to use Icons that really help me to see a page more quickly. As of now, we are restricted to the emoji's currently available. If there is any way to add the ability to use any image and upload it, that would be amazing!! Thanks

![Screenshot 2024-09-02 131647](https://github.com/user-attachments/assets/d647b2a9-8ca5-45e0-b320-d8bcd23685e7)

**Comment by Philipinho** [comment]
No plans to introduce custom icons for pages at this time. It will make things more complicated.
I am open to reviewing this in the future.

**Comment by sgnl05** [comment]
This might be the one missing feature that makes my company choose Outline over Docmost. :(

**Comment by Vringe** [comment]
@Philipinho I also missed this feature while comparing Outline with Docmost. Icons help organizing things and finding them easier. Maybe you can reconsider your decision, given that you got a substantial amount of downvotes? :-)

**Comment by cv5v** [comment]
I'm really looking forward to this feature being implemented. There are currently too few emoji options, so I'm forced to choose ones that aren't relevant.

**Comment by seh-len** [comment]
Yes, I really miss being able to use my own icons, too. Either by inserting SVG files or, even better, through a dedicated maintenance transaction for uploading my own icons. I also find that the existing icons lack multilingual search options.
