### ISSUE TITLE
websocket trying to connect ws://localhost:3000/collab

### ISSUE THREAD

**Issue by ATofighi** [docmost/docmost#247]
Hi, 

I upgrade my instance of docmost to 0.3.0, but after this upgrade, the websocket url seems to be localhost instead of `APP_URL`.. I run docmost in a kubernetes pod and use traefik as a ingress to expose it.

I think, this change cause the issue:

https://github.com/docmost/docmost/blob/8af2d4e8cf3358426d2f3f0312562e2530f421e9/apps/client/src/lib/config.ts#L14

**Comment by Philipinho** [comment]
Please upgrade to v0.3.1. It has been fixed.
