### ISSUE TITLE
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL

### ISSUE THREAD

**Issue by vnetesov** [docmost/docmost#253]
**Good afternoon! I run the docker compose with the following parameters:**

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://141.8.195.241:3000'
      APP_SECRET: '22baa38c0ba8d75c562a6d3dd40b744cba5892f024ea34f2e7487ee0e8d8fbcc'
      DATABASE_URL: 'postgresql://docmost:netit24Q_@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:

      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: netit24Q_
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:
  
  **I get an error**

> docmost@0.2.10 start /app
> pnpm --filter ./apps/server run start:prod

> server@0.2.10 start:prod /app/apps/server
> cross-env NODE_ENV=production node dist/main

(node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Nest] 41  - 09/03/2024, 3:11:18 PM     LOG [NestFactory] Starting Nest application...
/app/apps/server:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  server@0.2.10 start:prod: `cross-env NODE_ENV=production node dist/main`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

> docmost@0.2.10 start /app
> pnpm --filter ./apps/server run start:prod

> server@0.2.10 start:prod /app/apps/server
> cross-env NODE_ENV=production node dist/main

(node:40) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Nest] 40  - 09/03/2024, 3:14:11 PM     LOG [NestFactory] Starting Nest application...
[Nest] 40  - 09/03/2024, 3:14:20 PM     LOG [DatabaseModule] Establishing database connection

**please tell me what am I doing wrong?**

**Comment by Philipinho** [comment]
The pasted error log is confusing. Please share a screenshot of the logs.

**Comment by vnetesov** [comment]
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/47605cd2-a554-419f-a5a0-f2cbccfd999c">

**Comment by vnetesov** [comment]
> The pasted error log is confusing. Please share a screenshot of the logs.

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/21ce2cba-7a48-4e7c-a05c-a67599a637df">

**Comment by Philipinho** [comment]
From the logs, there are no reasons for shutting down, which is odd.
Can you try with the latest version?

**Comment by vnetesov** [comment]
> From the logs, there are no reasons for shutting down, which is odd. Can you try with the latest version?

I found out the reason. It turned out that the server was weak, so the containers did not have enough resources and they were constantly restarting. It seems to me that it would not be bad to write the minimum requirements for docmost. Thanks for the help

**Comment by Philipinho** [comment]
Glad to know. Thank you for the update.
