### ISSUE TITLE
pages showing nothing!!!

### ISSUE THREAD

**Issue by betheboy** [docmost/docmost#259]
When i was editing my page ,i can saw what am i editing !
But when i leave this page and returend to this page , nothing was there!!
There cames no logs!
Please help me to solve this problem,thanks
![image](https://github.com/user-attachments/assets/85817860-8def-4e63-9203-3b21861cebcb)

**Comment by Philipinho** [comment]
I assume you are on 0.3.0. Please upgrade to 0.3.1.

**Comment by Philipinho** [comment]
Can you please confirm if this issue persists after the upgrade?

**Comment by Philipinho** [comment]
Closing as this was fixed in v0.3.1. Feel free to reopen if you are still experiencing this issue.
