### ISSUE TITLE
Allow for wider text area

### ISSUE THREAD

**Issue by clbx** [docmost/docmost#26]
<img width="2048" alt="image" src="https://github.com/docmost/docmost/assets/15034517/22519691-14b4-4af4-adb3-549fc4d7d357">

It would be nice if the text would take up the entire screen instead of having so much wasted space.

**Comment by Philipinho** [comment]
That makes sense. I will work on it.

**Comment by Philipinho** [comment]
You can now configure your page width preference in v0.2.2.

Upgrade guide: https://docmost.com/docs/installation#upgrade
