### ISSUE TITLE
fresh installation backend connection error

### ISSUE THREAD

**Issue by AhmedCoolProjects** [docmost/docmost#260]
Hi, I still have the same issue from this one here: #28 , I tried to change the APP_URL, but didn't work, is there any idea what exactly I have to do!

![image](https://github.com/user-attachments/assets/f21278c0-1128-49d3-84f0-9cc97fc82c9d)

**Comment by Philipinho** [comment]
What version are you on?

**Comment by AhmedCoolProjects** [comment]
> What version are you on?

  this one here "version": "0.3.1",

**Comment by Philipinho** [comment]
Please paste your server logs.

**Comment by Philipinho** [comment]
You are in development mode. You have to manually run the database migrations.
`pnpm nx run server:migration:latest`

See https://docmost.com/docs/self-hosting/development#migrations.

**Comment by AhmedCoolProjects** [comment]
That was it, thank you so much for the fast reply 🫡

**Comment by AhmedCoolProjects** [comment]
`pnpm nx run server:migration:latest`  was the missing command for dev mode
