### ISSUE TITLE
Youtube URL are not exported to Markdown; when imported they stay as URL and don't get embedded

### ISSUE THREAD

**Issue by XorOverflow** [docmost/docmost#274]
When editing a page, pasting a URL of a youtube video transforms it as an embedded video. 

- If this page is exported to Markdown, the .md text does not contain any video URL.
- If a .md file (edited externally) contains normal URLs and Youtube video URLs and is imported as a new page, the page will display textual clickable URLs links for both. The Youtube  link is not converted to an embedded video.

Docmost version 0.3.1 installed by docker-compose

**Comment by Philipinho** [comment]
I will investigate. Thanks for reporting.

**Comment by Philipinho** [comment]
Missing YouTube URL in markdown export is now fixed.
