### ISSUE TITLE
[Bug] Can't paste into highlighted code block

### ISSUE THREAD

**Issue by X-lem** [docmost/docmost#291]
If I highlight a section of text in a code block I can't paste over it. I have to delete the text first then paste what's in my clipboard. Not a huge deal and can obviously workaround. Just wanted to make a note of it.

![image](https://github.com/user-attachments/assets/3e91c4da-7f2c-4182-885d-7f05c653ce2f)

Edit: Note this seems inconsistent. Sometimes it let's me paste. Not sure why. I generally used longer strings that highlighted stuff across multiple lines.

**Comment by Philipinho** [comment]
I am unable to reproduce this. Please let me know if it's still a problem for you.

**Comment by pedrolaranjeiro** [comment]
I had this issue and the console was throwing a Websocket error. If you use Nginx, the fix is [here](https://github.com/docmost/docmost/issues/553#issuecomment-2666413232)
