### ISSUE TITLE
[Feature Request] Import HTML files from web URL

### ISSUE THREAD

**Issue by AMDphreak** [docmost/docmost#295]
I am trying to move from Confluence, but importing articles from HTML does not import any images. Confluence allows me to view-source for a page, which I can then download; however, the images for the page are located in a folder on disk, which is not imported with the HTML.

Three improvements can be made to the import process.

It would be nice to instead import HTML from a URL.

Alternatively, for people with large Confluence knowledge-bases, use an API to download all articles from Confluence.

For those wishing to import HTML articles from other sources, it would be nice if you could import assets used in the HTML.

**Comment by Philipinho** [comment]
No plans to implement imports from URLs. 
However, there are plans to enhance the import process. We plan to introduce platform-specific imports, with support for 
 attachment imports too.
Let's track this here https://github.com/docmost/docmost/issues/343.
