### ISSUE TITLE
Wrong variables names in the documentation

### ISSUE THREAD

**Issue by foldfree** [docmost/docmost#30]
in https://docmost.com/docs/self-hosting/environment-variables

the following variables:

MAIL_HOST
MAIL_PORT
MAIL_USERNAME
MAIL_PASSWORD

should be:

SMTP_HOST
SMTP_PORT
SMTP_USERNAME
SMTP_PASSWORD

**Comment by Philipinho** [comment]
Thanks for reporting. Fixed https://github.com/docmost/docs/commit/1c5bc409b4ea5eb1f3feb0a40bc56ed98def5796.
