### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by WolniewiczBartek** [docmost/docmost#311]
Docmost itself is great, with darkmode it would be even better.

**Comment by WolniewiczBartek** [comment]
Nevermind XD

**Comment by sibelius** [comment]
do we have themes or darkmode ?

**Comment by Philipinho** [comment]
@sibelius  there is dark mode support. No themes.

**Comment by sibelius** [comment]
<img width="1496" alt="Image" src="https://github.com/user-attachments/assets/fe3acd3e-cba1-47fd-aa28-e7cb6f43b8bb" />

I think it would be good to have a toggle in the navigation bar

so we can easily change from light to dark 

<img width="45" alt="Image" src="https://github.com/user-attachments/assets/38e31663-1a64-44c0-9906-9fd8a5310240" />

like moon and sun icons

can we send a pull request to add this ?

**Comment by Philipinho** [comment]
@sibelius you can send a PR. Should be in the drop down menu.

**Comment by Philipinho** [comment]
@sibelius see https://github.com/docmost/docmost/pull/1369.
