### ISSUE TITLE
[BUG] Excalidraw color scheme changes on client's color scheme

### ISSUE THREAD

**Issue by RedNicStone** [docmost/docmost#312]
The color scheme of excalidraw images depend on the client's browser color scheme (light/dark mode).
If a party in light mode saves the image, it appears normal to them but the colors are inverted to parties in dark mode and vice versa.

Here is an example diagram that was saved by a light-mode user viewed by a light mode client:
![image](https://github.com/user-attachments/assets/08b6194a-e7a8-435a-beec-c793abc86e40)

Here is the same diagram after a dark mode user has opened and saved the digram:
![image](https://github.com/user-attachments/assets/ee16d18a-763c-441c-8b1d-6664f65fdc3f)

**Comment by Philipinho** [comment]
What is an ideal behavior for you?

**Comment by Philipinho** [comment]
I have changed the settings to stick with light mode on save https://github.com/docmost/docmost/commit/9e0fbae1debae93e7d93b6e0f24f87ca36affcfd.
We can only stick to one.
