### ISSUE TITLE
[Feature Request] Allow copying invite links

### ISSUE THREAD

**Issue by RedNicStone** [docmost/docmost#314]
Currently, In order to invite another user that invite has to be sent via an email server (SMTP or Postman).
While this may be the desired way to handle this in a larger organization, smaller set-ups may not want to tackle setting up a mail server.

For this reason it may be useful to add a simple 'copy invite link' button to the user management interface. That way users may be free to send this link by their own means rather than having to rely on the mail service alone.

This would be relatively trivial to set up since all data require to put together the invite is already present in the database and it would tremendously helpful.

Currently for our instance we have a dummy SMTP server set up that all outgoing mail is sent to, so that a server administrator may log into the server and retrieve the link contained in the message.

**Comment by Philipinho** [comment]
See https://github.com/docmost/docmost/issues/63.
