### ISSUE TITLE
[Feature Request] Excalidraw Live Collab

### ISSUE THREAD

**Issue by RusticCraftsman** [docmost/docmost#315]
In the actual docmost version, v0.3.1 , live collab is limited to text , We could extend this further to excalidraw leveraging on the already integrated live collab feature that excalidraw contains.

# How does it work for a normal user

## In normal scenario inside excalidraw.com, a user wanting to live collab would do the following:

1.Click on the live collaboration menu option
![image](https://github.com/user-attachments/assets/9f6370b9-1dc1-4115-9d01-34fe42ac9bc1)

2.Click on the start session button on the middle of the screen
![image](https://github.com/user-attachments/assets/2a9920f4-f4b7-4d87-a38a-ecfa7597dbe5)

3.Set your username
![image](https://github.com/user-attachments/assets/30c7ff25-55f9-4deb-bf76-8bc353cc8df8)

4.Copy the invite link
![image](https://github.com/user-attachments/assets/ebcb607d-3c99-4580-b759-58e22c931fec)

5.Invite some friends

6.Draw
![image](https://github.com/user-attachments/assets/e06f1c29-0e8b-4ec9-91af-fae5c0313dad)

8.End live collaboration
![image](https://github.com/user-attachments/assets/e1bc1d05-bde0-4ee9-80d2-c2cc8d12c4c0)

9.Exit

# How could we implement it in docmost

## It would be pretty conceptually simple:

START
the first user opens the excalidraw, this will initiate an excalidraw session
live collab would automatically be enabled, username would be set to the username in docmost
the excalidraw file presented in docmost would only point to the invite link of the live share, hence every user that tries to edit in their own session will join the live collab instead, username would also be set to the one in docmost.
After everyone leaves, stop live collab session and save changes.
return to start state

We could also make the server the one starting the sessiong, making the first user send a request that gets a response with an invite link.

What if 2 users click the same excalidraw canvas at the same time? We shall make it so there only can be 1 session of the same excalidraw canvas at the same time, based on periodic checking after start, the server should redirect the latest one to the invite link of the session that the first user started

**Comment by Shadowfita** [comment]
It would be great if there was a form of in-line editing available within a page that could make collaboration more seamless as well.

**Comment by Philipinho** [comment]
Live collaboration is not readily available on the Excalidraw react component we are using. No plans to implement this internally. 

We will eventually introduce an Excalidraw iframe embed option which can serve as a workaround where you collaborate directly on their website.
