### ISSUE TITLE
[Feature request] code support for PowerShell

### ISSUE THREAD

**Issue by ados8** [docmost/docmost#318]
Can the code blocks be expanded to support additional syntaxes such as PowerShell please.

**Comment by Philipinho** [comment]
Any more specific syntax suggestions?

**Comment by Shadowfita** [comment]
> Any more specific syntax suggestions?

Is there a way for the plugin used for highlighting to auto-load the most common? C#, javascript, typescript, powershell, etc.

**Comment by Shadowfita** [comment]
> @Shadowfita the most common languages are already present. I have added a few more in my open PR.

Awesome
