### ISSUE TITLE
[Feature request] Import from Outline

### ISSUE THREAD

**Issue by thelazyoxymoron** [docmost/docmost#323]
Hi, love the way this app has grown. I wanted to see if there's an easier way to enable migration from Outline.

I've been using Outline as our team wiki for some time, really like using it except for one crucial missing element - excalidraw support. With the recent support embedded in docmost, I'd be very keen to switch if there was an easier path for migration.

**Comment by Philipinho** [comment]
We should track this here https://github.com/docmost/docmost/issues/343.
