### ISSUE TITLE
Join forces with Outline

### ISSUE THREAD

**Issue by p4trizio** [docmost/docmost#33]
I noticed today the Docmost repository, what an awesome tool!
It looks very similar to another one I'm using in the past years: https://github.com/outline/outline

Maybe join forces would be great!

**Comment by Philipinho** [comment]
Thank you for stopping by. I appreciate it. It's been a year worth of effort and I am glad it resonates with so many people.

Outline is a great project and beautifully designed.
Can you expand more on the "join forces"? it would give me a good understanding of the scope.

**Comment by Philipinho** [comment]
Closing to keep issues clean.
