### ISSUE TITLE
[FEATURE REQUEST] Collapsible Nested Items

### ISSUE THREAD

**Issue by Cramses** [docmost/docmost#332]
![Screenshot 2024-09-20 at 08 53 41](https://github.com/user-attachments/assets/1028bf8c-0d3a-4197-84ae-269ed0945a53)

I'd like to suggest a new feature: collapsible nested items. 
I think it would be great if we could add a toggle option to expand or collapse child items under parent items. This would be really useful for organizing hierarchical content like nested lists or file structures.

I believe this feature would make the interface cleaner and easier to navigate, especially for pages with lots of nested information. It would help users focus on the most relevant parts of the content.

**Comment by Philipinho** [comment]
No plans to implement this.
As a workaround, you can use the toggle block.
