### ISSUE TITLE
[ Feature Request ] :  Forgot password functionality in sign in page.

### ISSUE THREAD

**Issue by MPD12340** [docmost/docmost#335]
I made an account some days ago but now as I go and run docker compose up I get login page and I cannot even reset my password as I forgot the previous one.

![Screenshot from 2024-09-20 22-11-39](https://github.com/user-attachments/assets/34eabf61-8044-46b5-a233-dc5ea5701887)

**Comment by Philipinho** [comment]
Password reset will be available in the next release.
For now you can try the workaround here: https://github.com/docmost/docmost/issues/182#issuecomment-2340705073
