### ISSUE TITLE
[Feature Request] Add Progressive Web App Functionality

### ISSUE THREAD

**Issue by sujayxaradhya** [docmost/docmost#341]
This is really a huge need to access from any device. Accessibility and installation from other devices is right now a barrier for teams to adapt Docmost instead of Notion for their daily use. So, please consider adding this feature in upcoming commits.
Thank you for your time that you guys have made this great tool.

I hope and wish to see Docmost to cross the horizon in the going on competition.

**Comment by Philipinho** [comment]
Existing issue https://github.com/docmost/docmost/issues/328.
