### ISSUE TITLE
Backspace will remove the page unexpectly!

### ISSUE THREAD

**Issue by ATofighi** [docmost/docmost#372]
Yesterday, I understand that if you click on the page list on the left of docmost, and then, key down backspace, the page will be removed without any question and I can't restore it using Ctrl+Z or any other way!!

I think this is bad UX, at least a confirmation needed for removing a page, also there are no soft-delete to allow to restore the unexpected removed  page.

**Comment by Philipinho** [comment]
Thanks for reporting. 
It has to do with the page tree shortcut keys. It will be fixed soon.
