### ISSUE TITLE
[Feature Request] Automatically backup docmost database to S3

### ISSUE THREAD

**Issue by aayushchugh** [docmost/docmost#374]
We can setup a cron job that will automatically backup the database using `pg_dump` and then upload it to s3.

**Comment by Philipinho** [comment]
Built-in database backup system is out of scope. Rather, we will create guides for such.

**Comment by WayneBooth** [comment]
Did these docs ever get created?
I can't rely on this service until I can backup the data.

**Comment by RikudouGoku** [comment]
> Did these docs ever get created? I can't rely on this service until I can backup the data.

Wanna know as well. Otherwise I think using a separate backup solution like Zerobyte (Restic) may work.
