### ISSUE TITLE
How to publish as a public webpage?

### ISSUE THREAD

**Issue by geekyouth** [docmost/docmost#384]
How to publish as a public webpage?

![image](https://github.com/user-attachments/assets/5ec67a05-1713-4fbb-bb65-74df5cee2d10)

**Comment by aayushchugh** [comment]
You can't publish it as a public webpage yet, it is made as a private tool. But many people are requesting this feature so there are chances that this feature might get shipped in future.

**Comment by Philipinho** [comment]
Already tracking this here https://github.com/docmost/docmost/issues/23.

**Comment by aayushchugh** [comment]
It would be great to pin #23 as a lot of users are raising this issue
