### ISSUE TITLE
Pages not staying in left sidebar

### ISSUE THREAD

**Issue by nothing2obvi** [docmost/docmost#40]
If I create a new page, type something, navigate to another button, press `Home`, then press `General` again, the page is no longer listed in the left sidebar.

Docmost 0.2.1 via Docker.

![Screenshot 2024-07-02 at 10 39 22 PM](https://github.com/docmost/docmost/assets/85228035/130abd30-d76a-47aa-99dd-d6326028fc92)

**Comment by Philipinho** [comment]
I noticed it too. 
It happens only when the first sidebar pages are created and the user navigates to a different page.

When you refresh the page, the sidebar pages appears and as work as normal from there onwards without this issue.

I will look into.

**Comment by Philipinho** [comment]
Fixed in v0.2.3, please upgrade to the latest version of Docmost.
