### ISSUE TITLE
New Feature: Add avatar images to Spaces and Groups

### ISSUE THREAD

**Issue by leadvic** [docmost/docmost#406]
I think it would be great for customization and user experience to add avatar images in the Spaces and Groups, similarly as it is already implemented for each individual user to upload a photo as an avatar.

![image](https://github.com/user-attachments/assets/cdf57d5b-beee-4a5d-9db6-71d7558355aa)
Like this but for spaces and groups. In spaces it should be in the settings section and in groups it could be in the edit options.

**Comment by Philipinho** [comment]
Closing in favour of #146.
