### ISSUE TITLE
Letters with accents misinterpreted on DrawIO (UTF8?)

### ISSUE THREAD

**Issue by Raumy** [docmost/docmost#408]
Hello,

When using accented letters, "é" for example, in DrawIO, once saved the image that is displayed on the page contains a sequence of characters. UTF8 conversion problem ?

![image](https://github.com/user-attachments/assets/7354f9ba-0b5b-4e09-8953-9b9deee7f6ef)

Thanks

**Comment by Philipinho** [comment]
What version are you on? It’s fixed on the latest version.

**Comment by Raumy** [comment]
hello,

My bad, I've didnt see new version.. Thanks :)
