### ISSUE TITLE
Page heading is partially cut

### ISSUE THREAD

**Issue by i5hi** [docmost/docmost#410]
First off, great work on this project! 

We just setup a self-hosted instance and in the process of migrating from gitbook.

**Small UI Bug:**
The heading of the page is sometimes cut a little bit from the top. Its not consistent; happens only on some pages.

![image](https://github.com/user-attachments/assets/dc9792b1-8ade-4e6d-a79e-3fca2db2e928)

**Comment by i5hi** [comment]
Seems to be related to adding an Emoji

**Comment by Philipinho** [comment]
Can I please know your OS and Browser?

**Comment by i5hi** [comment]
OS is archlinux
Browser is firefox

**Comment by i5hi** [comment]
Able to reproduce on Chrome as well
