### ISSUE TITLE
Enhancement: Add new member, group selection

### ISSUE THREAD

**Issue by leadvic** [docmost/docmost#415]
Hi there!

When adding a new member I think you should avoid show the option to the group everyone, as it is default and the user will get into that group ether way, so it doesn't make sense to show it.
![image](https://github.com/user-attachments/assets/5aeb6710-4832-4c90-b5e7-70fab85646cb)

**Comment by Philipinho** [comment]
Fixed https://github.com/docmost/docmost/commit/ba32e42ece50bf0d528ed3ea90e4c7ab0892fb4c.
