### ISSUE TITLE
New Feature: Add a PDF preview

### ISSUE THREAD

**Issue by leadvic** [docmost/docmost#416]
Hi there,

It would be crazy good if when uploading a PDF file it could be preview in Docmost itself instead of downloading it to see it on my computer, so I can read the PDF file without having to get out from Docmost.

I don't think everyone would want to have the PDF in a permanent preview way, I think it would be nice if the PDF files as attached files have two options, 1 download, and 2 preview. And the preview should not be a pop-up as it is usually annoying, but a Lightbox would be great or something similar.

![cHIV6](https://github.com/user-attachments/assets/85a5a242-14e6-41df-b966-82d71476b91d)

Like this for example

**Comment by DavidMoffatt-web** [comment]
I think this would be excellent. It would also be nice to rename a PDF as well.

**Comment by Philipinho** [comment]
Implemented.
~No plans for this yet. I might reconsider in the future.~

**Comment by NikJen26** [comment]
There is a kinda Workaround. Upload the file as "File Attachment" to Docmost. Copy the Downloadlink to Clipboard. Add a "Iframe Embedding" to your page and insert the copied link into it. Done!
