### ISSUE TITLE
[Feature Request] Add a .zip preview

### ISSUE THREAD

**Issue by leadvic** [docmost/docmost#417]
Hi there,

It would be awesome if you could upload a .zip file in Docmost and then use a preview option to check what is inside, similar to what google drive does.

![image](https://github.com/user-attachments/assets/10c877c9-cd1f-47e1-8832-4146e352a5e9)

At least for me, being able to see what is inside the .zip file before downloading help me make sure I'm downloading the correct one.

**Comment by Philipinho** [comment]
While it might be nice to have, I believe this feature is not within the scope of what we are trying to build.
