### ISSUE TITLE
Unable to delete space or edit space slug

### ISSUE THREAD

**Issue by jasonvanhattum** [docmost/docmost#42]
There doesn't seem to be any way to delete a space or edit the space slug. I realise I could do this directly in the database but it feels risky. Thanks.

**Comment by Philipinho** [comment]
It’s not here yet but will come soon.

**Comment by thokich** [comment]
I have create wrong spaces and want to delete them. I wait for your Update

**Comment by abramter** [comment]
Ya this would be very handy. Any ETA yet.

**Comment by kinkuroai** [comment]
Also waiting for this. I have a few unwanted spaces I used for tests.

**Comment by Philipinho** [comment]
It will be available in the next version release.

**Comment by danielpopovici745** [comment]
So how do you actually delete a space? I am not seeing a way to do so via UI

**Comment by Philipinho** [comment]
@danielpopovici745 the release is not yet out.
