### ISSUE TITLE
Bug: Excalidraw does not persist scheme settings

### ISSUE THREAD

**Issue by roleforgaming** [docmost/docmost#421]
OS: Windows
Browser: Chrome

ETA: I've also noticed that the font selection does not render once saved. 

Expected behavior: When I use excalidraw and assign it the dark color scheme, the color scheme should persist.

Actual behavior: When I save and exit my excalidraw drawing, then re-enter it, it defaults to light color scheme.

How to replicate: Create excalidraw drawing. Click hamburger menu. Click dark mode. Click save and exit. Reload drawing. Defaults to light mode.

[bug.webm](https://github.com/user-attachments/assets/61049650-4920-49bd-9170-494c31dbb434)

**Comment by Philipinho** [comment]
Fixed https://github.com/docmost/docmost/commit/31feb38def78fc4ef5d7610fed804faa3f57805a.
