### ISSUE TITLE
Images not displaying in Firefox

### ISSUE THREAD

**Issue by jasonvanhattum** [docmost/docmost#43]
Images not displaying in Firefox (latest).

I tried all of the following:
- Pasting into the browser
- Dragging into the browser
- Using the file upload dialog

Result is a blank area and a tiny blue square:

![CleanShot 2024-07-03 at 21 04 17](https://github.com/docmost/docmost/assets/21068767/40f92f07-6e69-4c2e-a282-72272af9bc70)

They display fine in Safari (latest).

**Comment by Philipinho** [comment]
Working on it. See https://github.com/docmost/docmost/pull/27.
It has to do with the CSS flex for image alignment.

**Comment by Philipinho** [comment]
Please upgrade to v0.2.2 to get the fix.

Upgrade guide: https://docmost.com/docs/installation#upgrade
