### ISSUE TITLE
E-Mail Overflows in Profile View

### ISSUE THREAD

**Issue by Capsicum42** [docmost/docmost#433]
With a long e-mail adress the e-mail flows outside of the window.

This is a minor issue.

<img width="157" alt="SCR-20241024-htzz-2" src="https://github.com/user-attachments/assets/5a834773-f4bb-4565-9cce-6b9e596e292c">

Regards
Holger

**Comment by Philipinho** [comment]
fixed https://github.com/docmost/docmost/commit/a574d13f43ac58e0094096f14b2b476fc50bc2c2.
