### ISSUE TITLE
Truncated Menu Items

### ISSUE THREAD

**Issue by AG-Novae** [docmost/docmost#435]
The menu on the left is not resizable. Long titles should either wrap onto multiple lines or display the full title on hover.

**Comment by Philipinho** [comment]
Can you please provide screenshots?

**Comment by AG-Novae** [comment]
Yes, the page tree menu items are truncated if they are too long

![image](https://github.com/user-attachments/assets/8cf14fee-2b1a-4243-b0ee-a19904837946)

**Comment by Philipinho** [comment]
In the next version, you will be able to resize the sidebar https://github.com/docmost/docmost/pull/452.
