### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by l4rm4nd** [docmost/docmost#46]
Hey,

many thanks for this great project.

Following feature requests:

- Multi-Factor-Authentication (TOTP, Webauthn Yubikey)
- ~~Syntax highlighting for code (maybe prism javascript?)~~
- Single Sign On / OIDC
- Prompting the user to input a new password twice to ensure it was correctly typed in during a password change
- Export and import features

Quite a lot but just an idea for the next milestones. 

Sure you were thinking about those already.

**Comment by Philipinho** [comment]
Good list. Thanks for suggesting. Have you got any more ideas?

Just to point out, the code block supports syntax highlighting already.

**Comment by matbgn** [comment]
Maybe at the very beginning, importing and exporting a single page as Markdown would be sufficient. BTW, do you have any master plan for its integration ? Do we talk from weeks, months, or semesters ?

Afterward, exporting (importing) a whole collection would be really, really nice cause it opens the door for complete migration to Docmost.

**Comment by Philipinho** [comment]
Hi @matbgn, I do not have a timeline, but I would say it is part of my current areas of interest.

**Comment by Philipinho** [comment]
Individual page exports in HTML and Markdown formats will come in the next release.

**Comment by matbgn** [comment]
:muscle: But most important to make reliable tests for me, would be the import capacity but I assume this is pretty near also.

**Comment by Philipinho** [comment]
Page export is available in [v0.2.5](https://github.com/docmost/docmost/releases/tag/v0.2.5).
I will now pay more attention to imports.

**Comment by Philipinho** [comment]
It is now possible to import Markdown and HTML pages in [v0.2.7](https://github.com/docmost/docmost/releases/tag/v0.2.7).

I will be closing this issue now. 
Feel free to create a standalone issue for MFA.
