### ISSUE TITLE
oauth/sso account intergration for authentik/authelia

### ISSUE THREAD

**Issue by LeeTeng2001** [docmost/docmost#466]
Most self hosted applications integrate logins with a custom SSO provider, it would be great to have this option

**Comment by DrMxrcy** [comment]
+1

**Comment by knperiyasamy** [comment]
+1

**Comment by Philipinho** [comment]
There is an open OIDC feature request [here](https://github.com/docmost/docmost/issues/22).
I expressed my thoughts https://github.com/docmost/docmost/issues/22#issuecomment-2211018048.

**Comment by ajb3932** [comment]
+1
