### ISSUE TITLE
Feature Request - PDF/File Attachments

### ISSUE THREAD

**Issue by DavidMoffatt-web** [docmost/docmost#47]
It would be excellent to be able to attach PDF's to pages as well.

I believe in a reddit thread it was mentioned this was in the plans already but just throwing my support for this one!

**Comment by Philipinho** [comment]
File attachments will come in the next version.
<img width="1354" alt="Screenshot 2024-08-21 at 20 08 24" src="https://github.com/user-attachments/assets/bd5a20b5-8787-4845-9a1e-51a28add411a">
