### ISSUE TITLE
[Feature request] Plugin ecosystem support

### ISSUE THREAD

**Issue by xBlady** [docmost/docmost#474]
Hello! 

Thank you for your great app!!

Please add option for developers to create plugins. We could have something similar to obsidian if plugins we're available to be created by anyone.

**Comment by Philipinho** [comment]
There are no plans to introduce a plugin architecture, at least not at this time.
I did give it a thought when I started working on the project. While it has its benefits, it will lead to maintenance and version compatibility burdens.
