### ISSUE TITLE
[Feature request] Public invite links

### ISSUE THREAD

**Issue by roablep** [docmost/docmost#493]
Ask: Add support for generating invite links to simplify user onboarding and collaboration, similar to platforms like Notion and Slack.

Invite links would allow users to invite others to join a space without needing to manually input email addresses. The links could include optional settings like:

- Expiration date: Links can expire after a specified time.
- Usage limit: Set a maximum number of users who can use the link.
- Permissions: Links can assign predefined roles or access levels.

Use Cases:

- Streamlining onboarding for new team members.
- Sharing access to specific projects or resources with external collaborators.
- Promoting adoption by enabling self-service invites.

Unsure of whether it should go under `/settings/members` or `s/general`

**Comment by enchove** [comment]
This is a really good idea.
If new users can just access docmost online, the admin doesn't need to set up SMTP.
I hate SMTP.....
But if we don't use SMTP, we're going to have to come up with some alternatives for the password retrieval feature.
Like requiring a user-set security question and an administrator-supplied random Password Reset code to be entered at the same time to retrieve the password.

**Comment by Philipinho** [comment]
There is an existing issue https://github.com/docmost/docmost/issues/63#issuecomment-2211717507.
The plan is similar. 
It will get worked on.
