### ISSUE TITLE
Utilise the AWS client's native credential parsing

### ISSUE THREAD

**Issue by will2hew** [docmost/docmost#50]
We currently provide the s3-client with credentials. The AWS NodeJS SDK will get these automatically if we don't provide it to the client. 

The downside of the current approach, is we can't use best-practice short lived AWS (or other) S3 credentials, which contains the extra `AWS_SESSION_TOKEN` environment variable.

This should simply be fixed by deleting this code, and the SDK will get the credentials automatically.

**Comment by will2hew** [comment]
@Philipinho your current PR doesn't quite fix this; AWS recommends using short lived credentials rather than long term. ones. We also need to use `AWS_SESSION_TOKEN` if available.

**Comment by Philipinho** [comment]
@will2hew even when the `credential` is no longer forced?
