### ISSUE TITLE
[Bug] pressing <Tab> while writing code changes focus to the language selection dropdown

### ISSUE THREAD

**Issue by neov5** [docmost/docmost#500]
Currently pressing tab while in the code editor changes focus to the language dropdown, making it very difficult to write larger snippets which involve indented blocks. Could this focus behaviour be fixed with a CSS/JS tweak, making it easier to write code with indents? Thanks!

**Comment by Philipinho** [comment]
Existing issue for Tab support https://github.com/docmost/docmost/issues/297.

**Comment by Philipinho** [comment]
I introduced an official fix for this here: https://github.com/docmost/docmost/pull/523.
It should be available in v0.6.
