### ISSUE TITLE
Page history not working

### ISSUE THREAD

**Issue by royklo** [docmost/docmost#525]
For some reason it seems that the page history is not working?

I added soms test data. Moved to other space. Returned, changed data. Moved again. After second return I could see anything in the page history.

Does something still needs to be enabled?

**Comment by Philipinho** [comment]
The page history is recorded 10 minutes after the last update.

**Comment by Philipinho** [comment]
Feel free to reopen if that’s not the case.

**Comment by madukan** [comment]
Would be good to have the page history saved as it updates. Let the admin configure the time to retain the history. That way the changes are fully recoded and recoverable in case of emergency. I noticed the history takes a bit long to come, didn't time myself to see if that's the said 10mins or so. I'm more keen on recording everything, even though its 10mins that's fine. But when processor is idling I think it can be earlier than that as well. Some food for thought..

**Comment by olivierlambert** [comment]
Even a manual save via Ctrl+S to "force" a save and if there's a diff, to save it in the history, plus the 10 min auto history save would be great! 👍
