### ISSUE TITLE
Feature Request: Disable code higlighting

### ISSUE THREAD

**Issue by denysvitali** [docmost/docmost#53]
It would be nice to be able to define whether syntax highlighting should be enabled or not in code blocks.

Currently the highlighter tries to guess the programming language (and this seems to work fine for most cases) - but it keeps the text weirdly highlighted in case of stuff that is supposed to not be highlighted (e.g: plain text files, logs, ...).

It would be nice to have a sort of drop-down to select the programming language, [similarly to what you can do in Google Docs](https://www.youtube.com/watch?v=HdAgRZ1ncS8), and have an option to select "Plaintext" or "No highlighting"

**Comment by hgouveia** [comment]
plus add the possibility to add code block using markdown

```
  .```{lang} 
     // my text
  .``` 
```

ex:
```
  .```php
     <?php // all good
  .``` 
```

**Comment by Philipinho** [comment]
@hgouveia you can do that already. Give space after typing the opening marks to get a code block.

**Comment by hgouveia** [comment]
> @hgouveia you can do that already. Give space after typing the opening marks to get a code block.

oh ok and the language specification also works?

**Comment by Philipinho** [comment]
@hgouveia yes, the language is picked up too.
