### ISSUE TITLE
Using Docker and Reverse Proxy Requires Specific APP_URL= Setting

### ISSUE THREAD

**Issue by Riftr** [docmost/docmost#553]
To use Docmost behind a reverse proxy such as Traefik on Docker requires you to set the APP_URL environment variable to:

`APP_URL=https://0.0.0.0:3000`

The problem is that the documentation at https://docmost.com/docs/installation doesn't reflect this and instead says:

> The APP_URL should be replaced with your chosen domain. E.g. https://example.com or https://docmost.example.com.

This could be updated with a note for Docker and reverse proxy users that you need to tell Docmost to listen on all networks in order for it to work in this setup.

**Comment by Philipinho** [comment]
The `APP_URL` has nothing to do with the docker network. Its usage is only for internal links and links in emails.

The server is by default configured to listen on all network interfaces.
https://github.com/docmost/docmost/blob/f48d6dd60bbe270fd19899dd5feae70d93d64be6/apps/server/src/main.ts#L68

**Comment by Philipinho** [comment]
Feel free to reopen if this issue persists.

**Comment by pedrolaranjeiro** [comment]
In my case the websocket was not working with the Nginx engine.
My original redirection with the websocket failing was:
```
location / {
    proxy_pass http://12.1.1.50:12786/
}
```
To make it work I added
 ```
location / {
    proxy_pass http://12.1.1.50:12786/
    # WebSocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

**Comment by arch-fan** [comment]
In my case I wasn't specifying the network which had the service. 
```yml
- "traefik.docker.network=proxied"
```
