### ISSUE TITLE
Email Setup Issue / Reset User

### ISSUE THREAD

**Issue by Th4tM0nk3y** [docmost/docmost#596]
Hi there, sorry if my issue is less of a code problem and rather more a "user error" problem - I hope you can help me either way.
A user of mine didn't write down their password and can't log in anymore, I am currently struggling with the email setup though.

I keep getting connection timeouts on the EmailProcessor Job.
The following are my _redacted_ settings in the docker compose file:
```
MAIL_DRIVER: smtp
SMTP_HOST: 'smtp.strato.de'
SMTP_PORT: 465
SMTP_USERNAME: 'noreply@TLD'
SMTP_PASSWORD: StrongPasswordHere
SMTP_SECURE: true
MAIL_FROM_ADDRESS: 'noreply@TLD'
MAIL_FROM_NAME: 'Docmost - Noreply'
```
Am i missing smth obvious or is Strato just not an option for the smtp server?

Is there another method how I could manually change the password for a user in the database? They have forgotten their password and I currently can't do a password reset through the UI as the emails are not working. Any help would be massively appreciated. (P.S. the container is running in a VM)

**Comment by alexandrovic-code** [comment]
(How) did you solve this issue? Facing the same problem

**Comment by Philipinho** [comment]
@alexandrovic-code if you don’t have SMTP enabled, you can use a service like https://bcrypt-generator.com/ to generate the password hash. Set the rounds to 12.
Copy the hashed password and update the password column for the user in the database with it.

Or use a fake SMTP service like https://ethereal.email/ to receive the email online.
