### ISSUE TITLE
Erros on docker install

### ISSUE THREAD

**Issue by thinkbig1979** [docmost/docmost#62]
Hi there,

I'm using compose to try and run your app.
I've used your compose file template, moved the password and secret into a .env file.
I've replaced the DB password in below example with `my-sontrng-password` so as not to expose my password here.
Unfortunately I'm faced with the following error:

```bash
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
Error: getaddrinfo ENOTFOUND redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'redis'
}
```
Any ideas...?

My compose file:

```yaml
version: "3"
services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    depends_on:
      - db
      - redis
    environment:
      APP_URL: https://my.app.url
      APP_SECRET: ${SECRET}
      DATABASE_URL: postgresql://docmost:my-strong-password@db:5432/docmost?schema=public
      REDIS_URL: redis://redis:6379
    #    ports:
    #      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data/storage
    networks:
      - nginxproxymanager_default
  db:
    image: postgres:16-alpine[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
Error: getaddrinfo ENOTFOUND redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'redis'
}

**Comment by Philipinho** [comment]
I am glad you figured it out yourself. 
I would love to hear your feedback and what you think is missing, if you've got any.
Thank you.

**Comment by thinkbig1979** [comment]
thanks @Philipinho, happy to provide some feedback of course:

I'm working with a team that uses Notion quite a bit, and one thing we all love is the 'databases' that you can view as kanban boards or tables etc. That currently does not exist in Docmost, and would be a killer addition.

**Comment by ultranity** [comment]
> thanks @Philipinho, happy to provide some feedback of course:
> 
> I'm working with a team that uses Notion quite a bit, and one thing we all love is the 'databases' that you can view as kanban boards or tables etc. That currently does not exist in Docmost, and would be a killer addition.

this feature will be quite cool and it deserve an extra issue/project dissusion!
