### ISSUE TITLE
Sign-in needs to be case insensitive for email

### ISSUE THREAD

**Issue by DavidMoffatt-web** [docmost/docmost#68]
I tried logging in with the first letter in my email capitalized and it wouldn't work. I thought I had used the wrong password, so I cleaned and re-created the entire instance, and used the same username and the password I thought I used the first time. My email was capitalized in the sign-up. When I went to log back in I faced the same issue.

What is needed: Make it so that emails are not case-sensitive.

**Comment by Philipinho** [comment]
I will fix this in the next release. Thanks for reporting.
