### ISSUE TITLE
Feature Request - Open API/Swagger Docs

### ISSUE THREAD

**Issue by rcronin** [docmost/docmost#75]
Hello,

Awesome app so far! This is shaping out to be exactly what my organization needs. I'd like to request a feature where a user could import a swagger doc file or point to a swagger json file and DocMost generate a page that builds documentation based on it. Similar to readthedocs basically. Would be really nice to have the API docs side by side with the technical docs.

**Comment by Philipinho** [comment]
This seems to be out of scope. I will revisit in the future, if needs be.
