### ISSUE TITLE
[bug] Invite Email Accept Invite Button not clickable

### ISSUE THREAD

**Issue by compgeniuses** [docmost/docmost#76]
I have a Docmost App for Nethserver 8 here: https://github.com/geniusdynamics/ns8-docmost/

Everything works according to plan, however, while sending Invite Emails, the sent email Accept Invite Button on the Email seems not to Accept Clicks.

![image](https://github.com/docmost/docmost/assets/16150798/bb40b347-58b6-40ca-ab10-320961e2caf2)
You could also Implement Alternative Link, without the button, incase there is issue with the button.

**Comment by Philipinho** [comment]
A plain link makes sense. Do you mind telling me what email client this is?

**Comment by compgeniuses** [comment]
> A plain link makes sense. Do you mind telling me what email client this is?

Using [EM client](https://www.emclient.com/)

**Comment by Philipinho** [comment]
Thank you.

**Comment by compgeniuses** [comment]
I think i have identifid why this is happening.

The link being sent out does not have HTTP:// or HTTPS:// appended, therefore the client is unable to work with the link as a a real link.

**Comment by Philipinho** [comment]
Did you add the protocol to the env `APP_URL` ?

**Comment by compgeniuses** [comment]
thats what i can notice 

I have defined # Configure HOST
HOST = data.get('host')
agent.set_env('APP_URL', HOST) which does not include protocol

Adjusting to, for testing
HOST = data.get('host')
SERVER_HOST = "https://"+host
agent.set_env('APP_URL', SERVER_HOST)

**Comment by compgeniuses** [comment]
Appending the Protocol fixes the issue...
