### ISSUE TITLE
FR: Tailscale-based authentication

### ISSUE THREAD

**Issue by khionu** [docmost/docmost#77]
Tailscale-based authentication is simple, but is a bit risky. Here's the flow I'm imagining to minimize risk:
1. Admin toggles Tailscale auth in the settings
2. Docmost begins watching for [the appropriate headers](https://tailscale.com/kb/1312/serve#identity-headers), but only if the request comes from `tailscale0` (by [getting the raw FD](https://github.com/nodejs/help/issues/1312#issuecomment-394138355) and then [using `getsockname(2)`](https://man7.org/linux/man-pages/man2/getsockname.2.html) ).
3. If an account already exists that matches the `Tailscale-User-Login` header, automatically link them. Else prompt them to login or create a new account, link this account with the `Tailscale-User-Login` header.
4. Automatically authenticate them with their linked account.

**Comment by Philipinho** [comment]
There are no plans to implement this form of authentication.
