### ISSUE TITLE
[Feature Request] Vim Editor mode

### ISSUE THREAD

**Issue by NeddM** [docmost/docmost#84]
Maybe in the future it could be nice to add Vim or Emacs editing modes. 

I know this option is not even in Notion, but could be a nice feature.

**Comment by Philipinho** [comment]
It will not be possible to support this due to the nature of the editor.

**Comment by juninhopo** [comment]
@Philipinho Can you explain why?

**Comment by jjhidalgar** [comment]
This would be awesome
