### ISSUE TITLE
pnpm nx run @docmost/editor-ext:build fails with: Cannot find module 'client/src/lib/types'

### ISSUE THREAD

**Issue by olivierIllogika** [docmost/docmost#86]
Following [development setup](https://docmost.com/docs/self-hosting/development) and running into this issue. Working on M1 with Monterey and nvm with node 20.12.2.

Modifying `packages/editor-ext/tsconfig.json` seems to fix it and it makes sense to me, but it feels like I shouldn't be the only one with this issue and I might be missing some obvious config setting 🤔 
```diff
-    "baseUrl": "./",
+    "baseUrl": "../../apps/",
```

<details>
<summary>pnpm nx run @docmost/editor-ext:build log</summary>

```
pnpm nx run @docmost/editor-ext:build

> nx run @docmost/editor-ext:build


> @docmost/editor-ext@ build /Users/omartin/development/docmost/packages/editor-ext
> tsc --build

src/lib/image/image-upload.ts:3:29 - error TS2307: Cannot find module 'client/src/lib/types' or its corresponding type declarations.

3 import { IAttachment } from "client/src/lib/types";
                              ~~~~~~~~~~~~~~~~~~~~~~

src/lib/video/video-upload.ts:3:29 - error TS2307: Cannot find module 'client/src/lib/types' or its corresponding type declarations.

3 import { IAttachment } from "client/src/lib/types";
                              ~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.

 ELIFECYCLE  Command failed with exit code 1.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target build for project @docmost/editor-ext (1s)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]


```
</details>

**Comment by Philipinho** [comment]
On M1 myself, I tried it on Node 20.12.2 with no issues.
It's quite strange how the mono-repo behaves differently on different systems.

I should give more attention to it.

**Comment by olivierIllogika** [comment]
> It's quite strange how the mono-repo behaves differently on different systems.

Got me thinking was could be different and the only thing might be the pnpm version installed.

I have 8.6.5 ; what's yours?

**Comment by Philipinho** [comment]
My pnpm version is 9.5.0.
