### ISSUE TITLE
New import feature keeps failing with Markdown but HTML works

### ISSUE THREAD

**Issue by ispjstfu** [docmost/docmost#91]
Can't really figure out why but here is what's happening in the console. I tested this with both Markdown files downloaded from Github (initially made with Gitbook) and all of those failed, and also by exporting a page as both Markdown and HTML from Notion where the HTML gets imported but the same page as Markdown fails.

<img width="2117" alt="SCR-20240720-ruex" src="https://github.com/user-attachments/assets/56fbba05-d19b-400b-bbc2-1b8d838703fb">

**Comment by Philipinho** [comment]
Is there any error on the server console?

**Comment by ispjstfu** [comment]
Oh, right. Yes. Here.
<img width="951" alt="SCR-20240720-sfsq" src="https://github.com/user-attachments/assets/d8c69f27-c2eb-4d82-95a0-9c2c0577b8b2">

**Comment by Philipinho** [comment]
Can you email me a non-sensitive faulty Markdown?
I can't seem to reproduce with Markdown exports from these platforms. 
(Email in Github profile). Thank you.

**Comment by GSKang94** [comment]
Hi I got same error from this small md file
`Test.md`
```md
# Test

### Lorem ipsum
```

**Comment by ispjstfu** [comment]
Hi,

Sure, here you go. This one is exported directly from Notion.

￼

Here is one from Gitbook that looks a bit more “strange” when opened in a text editor:

￼

Ha en fin dag! / Have a nice day!
________________________________

Med vänlig hälsning / Best Regards

Elin Rein
***@***.***
+46 (0) 700 708151
elinrein.se

**Comment by Philipinho** [comment]
@ispjstfu Can you email to phil[at]docmost.com instead?
Your comment has no attachments.

**Comment by ispjstfu** [comment]
Alright. I replied to the comment via email so I thought maybe you got them there but I'll send a proper email now instesd.

**Comment by Philipinho** [comment]
I just released [v0.2.8](https://github.com/docmost/docmost/releases/tag/v0.2.8). I would appreciate your feedback if this issue still occurs.

**Comment by stanrc85** [comment]
I'm still having the same issue on my updated install.

**Comment by Philipinho** [comment]
Please post the server logs.

**Comment by stanrc85** [comment]
Here's the log from a few attempts 
![image](https://github.com/user-attachments/assets/be261b6a-5fbf-457c-8511-d057214abe8c)

**Comment by warfair1337** [comment]
Updated to 0.2.8 and I'm still having the same issue import markdown-files.
Tried multiple browsers, Safari, Firefox and Brave.
Also tried exporting a page as markdown from Docmost and re-import it, which also failed.

```
[Nest] 41  - 07/22/2024, 6:54:31 PM     LOG [NestFactory] Starting Nest application...
[Nest] 41  - 07/22/2024, 6:54:31 PM     LOG [DatabaseModule] Establishing database connection
[Nest] 41  - 07/22/2024, 6:54:31 PM     LOG [DatabaseModule] Database connection successful
[Nest] 41  - 07/22/2024, 6:54:31 PM     LOG [DatabaseMigrationService] No pending database migrations
[Nest] 41  - 07/22/2024, 6:54:31 PM     LOG [NestApplication] Nest application successfully started
[Nest] 41  - 07/22/2024, 6:54:45 PM   ERROR [ImportService] Failed to create ProseMirror state
```

**Comment by stanrc85** [comment]
I'm on Win11, Chrome browser

**Comment by Philipinho** [comment]
Can you check the mime type of the file as displayed on your windows file system?

**Comment by warfair1337** [comment]
Experiencing this on both MacOS 14.5 and Windows 11.
Tested on another machine running Pop OS 22.04 and here the import worked perfectly.

**Comment by stanrc85** [comment]
OS reports mime type is text/plain

**Comment by Philipinho** [comment]
Perfect. That’s the issue.
Your OS changes markdown mime type to text/plain instead of text/markdown. 
I should make it more lenient in the next release.

**Comment by warfair1337** [comment]
Pop OS and MacOS reports the same result, plain text.
Although, import from Pop OS works, but not MacOS.

```
file -i test.md
test.md: text/plain; charset=us-ascii
```

**Comment by Philipinho** [comment]
Please upgrade to [v0.2.9](https://github.com/docmost/docmost/releases/tag/v0.2.9) which aims to address this issue.
I look forward to your feedback.
Thank you.

**Comment by stanrc85** [comment]
Success, thank you!

**Comment by warfair1337** [comment]
Works perfectly now, thanks.

**Comment by ados8** [comment]
I found the importing didn't work until I fixed the docker permissions.
Seems markdown needs access to write to the data folder and once that was address I could import markdown files.

**Comment by matbgn** [comment]
The import is much better in v0.2.9 than it was originally in 0.2.7, many thanks indeed :confetti_ball: 

Still, I have a question on callouts, can you imagine any parser on import to handle the three main callouts types from Outilne that are really close to Docmost's?

:::warning
:::info
:::tip

![image](https://github.com/user-attachments/assets/34eeca35-5f0f-4458-af7b-7a7c5c5994df)

**Comment by Philipinho** [comment]
@matbgn Markdown callout import will be supported soon.

**Comment by Philipinho** [comment]
@matbgn markdown callout imports (with types e.g. info, warning) have been added and will be available in the next release.
