### ISSUE TITLE
"Password authentication failed for user "docmost""

### ISSUE THREAD

**Issue by mbkcontabilidade** [docmost/docmost#96]
Hi everyone. I follow the steps on the website, but still, no luck. Tried changing a couple of configs, still, no luck. Here is my compose, if anyone can spot what is wrong with it, will be much appreciated. 

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://192.168.0.111:3000/"
      APP_SECRET: "mbkcontabilidade"
      DATABASE_URL: "postgresql://docmost:mbkcontabilidade@d>
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: mbkcontabilidade
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
      
volumes:
  docmost:
  db_data:
  redis_data:
  
  Here is the log:
  
  root@docmost:~/docmost# docker container logs docmost-docmost-1

> docmost@0.2.7 start /app
> pnpm --filter ./apps/server run start:prod

> server@0.2.7 start:prod /app/apps/server
> cross-env NODE_ENV=production node dist/main

(node:40) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Nest] 40  - 07/21/2024, 6:06:14 AM     LOG [NestFactory] Starting Nest application...
[Nest] 40  - 07/21/2024, 6:06:15 AM     LOG [DatabaseModule] Establishing database connection
[Nest] 40  - 07/21/2024, 6:06:15 AM   ERROR [DatabaseModule] error: password authentication failed for user "docmost"
[Nest] 40  - 07/21/2024, 6:06:15 AM     LOG [DatabaseModule] Retrying [1/15] in 3 seconds
[Nest] 40  - 07/21/2024, 6:06:18 AM   ERROR [DatabaseModule] error: password authentication failed for user "docmost"
[Nest] 40  - 07/21/2024, 6:06:18 AM     LOG [DatabaseModule] Retrying [2/15] in 3 seconds
[Nest] 40  - 07/21/2024, 6:06:21 AM   ERROR [DatabaseModule] error: password authentication failed for user "docmost"
[Nest] 40  - 07/21/2024, 6:06:21 AM     LOG [DatabaseModule] Retrying [3/15] in 3 seconds
[Nest] 40  - 07/21/2024, 6:06:24 AM   ERROR [DatabaseModule] error: password authentication failed for user "docmost"
[Nest] 40  - 07/21/2024, 6:06:24 AM     LOG [DatabaseModule] Retrying [4/15] in 3 seconds
[Nest] 40  - 07/21/2024, 6:06:27 AM   ERROR [DatabaseModule] error: password authentication failed for user "docmost"
[Nest] 40  - 07/21/2024, 6:06:27 AM     LOG [DatabaseModule] Retrying [5/15] in 3 seconds
[Nest] 40  - 07/21/2024, 6:06:30 AM   ERROR [DatabaseModule] error: password authentication failed for user "docmost"
[Nest] 40  - 07/21/2024, 6:06:30 AM     LOG [DatabaseModule] Retrying [6/15] in 3 seconds
[Nest] 40  - 07/21/2024, 6:06:33 AM   ERROR [DatabaseModule] error: password authentication failed for user "docmost"
[Nest] 40  - 07/21/2024, 6:06:33 AM     LOG [DatabaseModule] Retrying [7/15] in 3 seconds
[Nest] 40  - 07/21/2024, 6:06:36 AM     LOG [DatabaseModule] Retrying [8/15] in 3 seconds
[Nest] 40  - 07/21/2024, 6:06:36 AM   ERROR [DatabaseModule] error: password authentication failed for user "docmost"

This is running on a proxmox lxc ubuntu 22.04, using docker latest stable update and compose v229

**Comment by Philipinho** [comment]
Do you have special characters in your Postgres password?

**Comment by mbkcontabilidade** [comment]
None, just simple 10 letter password. I even tried again on a new container, no luck. Tried different passwords, parameters, nothing. Got no clue why postgres is not recognizing the password.

**Comment by Philipinho** [comment]
Can you try deleting the Postgres’s `db_data` volume and then start with a fresh compose file?

**Comment by mbkcontabilidade** [comment]
Sure, let's try that. 

Ok, so you figured it out, the mistake i made on both installs was: i eagerly did docker compose up -d and then realized i forgot something, changed the docker-compose.yml, and did a compose up -d again, but the volumes did not change, just the containers, so the password was not matching. 

Thanks again.

**Comment by BrentJMaxwell** [comment]
Thanks guys! I'm using Portainer and had this same error. Web search brought me here.

If anyone has the same problem, rebuild your external docker volume for postgresql.

I assume the original reason for the error was a special character in the password (# in my case) that isn't being escaped correctly in the URL string. So probably avoid special characters when creating a password for the DB.

**Comment by guo-fan-sun** [comment]
Maybe you didn't replace STRONG_DB_PASSWORD the first time. Even if you replace it later, you will still get an error. You need to run `docker compose down --volumes`

**Comment by gjimenezl** [comment]
Thanks for your kind answer...! It is working for me successfully...!
