### ISSUE TITLE
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  server@0.2.7 start:prod: `cross-env NODE_ENV=production node dist/main` Exit status 1  ELIFECYCLE  Command failed with exit code 1.

### ISSUE THREAD

**Issue by AndyZoeng** [docmost/docmost#97]

**Comment by Philipinho** [comment]
Can I see a screenshot of the full server log?

**Comment by AndyZoeng** [comment]
![WX20240721-163629@2x](https://github.com/user-attachments/assets/58a7a9b1-2363-4dec-a1a8-8e6b07a1e5b5)

**Comment by Philipinho** [comment]
It complains of your APP_URL. It has to be a valid URL format starting with http or https.

**Comment by AndyZoeng** [comment]
Thanks for getting back to me!

I understand now that the APP_URL needs to be a valid URL format. You are correct, it wasn't a required field during the installation on Unraid, so I left it blank.

**Comment by AndyZoeng** [comment]
![Uploading WX20240721-165018@2x.png…]()

**Comment by AndyZoeng** [comment]
![WX20240721-165018@2x](https://github.com/user-attachments/assets/9f634b6e-cc0e-436f-8d63-e623dca214a5)

**Comment by Philipinho** [comment]
I see. If you wish to leave it blank, you should comment it out.

**Comment by bgriffen** [comment]
I also am getting a 502 gateway error. Though when I try to even click the logs in opens the terminal window then just instantly closes again. I then just left the app_url blank on the advice above (for now).  Is there some other way to view the logs? I can connect to the postgres instance from another computer as well as the redis instance but can't workout why it's crashing although saying "Ready" on the front page of my apps list.

**Comment by Philipinho** [comment]
@bgriffen do you still experience the syncing issue?

**Comment by Pawel-Bedn4rczyk** [comment]
Yes to avoid this error. Put valid APP_URL and strong  APP_SECRET with minimum 32 characters.
